generated_launchpad/include/sys_pmu.h File Reference
System Pmu Header File.
#include `sys_common.h`
Macros
#define pmuCOUNTER0 0x00000001U
pmu event counter 0 mask
#define pmuCOUNTER1 0x00000002U
pmu event counter 1 mask
#define pmuCOUNTER2 0x00000004U
pmu event counter 2 mask
#define pmuCYCLE_COUNTER 0x80000000U
pmu cycle counter mask
Enumerations
enum pmuEvent {
PMU_INST_CACHE_MISS = 0x01U,
PMU_DATA_CACHE_MISS = 0x03U,
PMU_DATA_CACHE_ACCESS = 0x04U,
PMU_DATA_READ_ARCH_EXECUTED = 0x06U,
PMU_DATA_WRITE_ARCH_EXECUTED = 0x07U,
PMU_INST_ARCH_EXECUTED = 0x08U,
PMU_EXCEPTION_TAKEN = 0x09U,
PMU_EXCEPTION_RETURN_ARCH_EXECUTED = 0x0AU,
PMU_CHANGE_TO_CONTEXT_ID_EXECUTED = 0x0BU,
PMU_SW_CHANGE_OF_PC_ARCH_EXECUTED = 0x0CU,
PMU_BRANCH_IMM_INST_ARCH_EXECUTED = 0x0DU,
PMU_PROC_RETURN_ARCH_EXECUTED = 0x0EU,
PMU_UNALIGNED_ACCESS_ARCH_EXECUTED = 0x0FU,
PMU_BRANCH_MISSPREDICTED = 0x10U,
PMU_CYCLE_COUNT = 0x11U,
PMU_PREDICTABLE_BRANCHES = 0x12U,
PMU_INST_BUFFER_STALL = 0x40U,
PMU_DATA_DEPENDENCY_INST_STALL = 0x41U,
PMU_DATA_CACHE_WRITE_BACK = 0x42U,
PMU_EXT_MEMORY_REQUEST = 0x43U,
PMU_LSU_BUSY_STALL = 0x44U,
PMU_FORCED_DRAIN_OFSTORE_BUFFER = 0x45U,
PMU_FIQ_DISABLED_CYCLE_COUNT = 0x46U,
PMU_IRQ_DISABLED_CYCLE_COUNT = 0x47U,
PMU_ETMEXTOUT_0 = 0x48U,
PMU_ETMEXTOUT_1 = 0x49U,
PMU_INST_CACHE_TAG_ECC_ERROR = 0x4AU,
PMU_INST_CACHE_DATA_ECC_ERROR = 0x4BU,
PMU_DATA_CACHE_TAG_ECC_ERROR = 0x4CU,
PMU_DATA_CACHE_DATA_ECC_ERROR = 0x4DU,
PMU_TCM_FATAL_ECC_ERROR_PREFETCH = 0x4EU,
PMU_TCM_FATAL_ECC_ERROR_LOAD_STORE = 0x4FU,
PMU_STORE_BUFFER_MERGE = 0x50U,
PMU_LSU_STALL_STORE_BUFFER_FULL = 0x51U,
PMU_LSU_STALL_STORE_QUEUE_FULL = 0x52U,
PMU_INTEGER_DIV_EXECUTED = 0x53U,
PMU_STALL_INTEGER_DIV = 0x54U,
PMU_PLD_INST_LINE_FILL = 0x55U,
PMU_PLD_INST_NO_LINE_FILL = 0x56U,
PMU_NON_CACHEABLE_ACCESS_AXI_MASTER = 0x57U,
PMU_INST_CACHE_ACCESS = 0x58U,
PMU_DOUBLE_DATA_CACHE_ISSUE = 0x59U,
PMU_DUAL_ISSUE_CASE_A = 0x5AU,
PMU_DUAL_ISSUE_CASE_B1_B2_F2_F2D = 0x5BU,
PMU_DUAL_ISSUE_OTHER = 0x5CU,
PMU_DP_FLOAT_INST_EXCECUTED = 0x5DU,
PMU_DUAL_ISSUED_PAIR_INST_ARCH_EXECUTED = 0x5EU,
PMU_DATA_CACHE_DATA_FATAL_ECC_ERROR = 0x60U,
PMU_DATA_CACHE_TAG_FATAL_ECC_ERROR = 0x61U,
PMU_PROCESSOR_LIVE_LOCK = 0x62U,
PMU_ATCM_MULTI_BIT_ECC_ERROR = 0x64U,
PMU_B0TCM_MULTI_BIT_ECC_ERROR = 0x65U,
PMU_B1TCM_MULTI_BIT_ECC_ERROR = 0x66U,
PMU_ATCM_SINGLE_BIT_ECC_ERROR = 0x67U,
PMU_B0TCM_SINGLE_BIT_ECC_ERROR = 0x68U,
PMU_B1TCM_SINGLE_BIT_ECC_ERROR = 0x69U,
PMU_TCM_COR_ECC_ERROR_LOAD_STORE = 0x6AU,
PMU_TCM_COR_ECC_ERROR_PREFETCH = 0x6BU,
PMU_TCM_FATAL_ECC_ERROR_AXI_SLAVE = 0x6CU,
PMU_TCM_COR_ECC_ERROR_AXI_SLAVE = 0x6DU
 }
pmu event
Functions
void _pmuInit_ (void)
Initialize Performance Monitor Unit.
void _pmuEnableCountersGlobal_ (void)
Enable and reset cycle counter and all 3 event counters.
void _pmuDisableCountersGlobal_ (void)
Disable cycle counter and all 3 event counters.
void _pmuResetCycleCounter_ (void)
Reset cycle counter.
void _pmuResetEventCounters_ (void)
Reset event counters 0-2.
void _pmuResetCounters_ (void)
Reset cycle counter and event counters 0-2.
void _pmuStartCounters_ (uint32 counters)
Starts selected counters.
void _pmuStopCounters_ (uint32 counters)
Stops selected counters.
void _pmuSetCountEvent_ (uint32 counter, uint32 event)
Set event counter count event.
uint32 _pmuGetCycleCount_ (void)
Returns current cycle counter value.
uint32 _pmuGetEventCount_ (uint32 counter)
Returns current event counter value.
uint32 _pmuGetOverflow_ (void)
Returns current overflow register and clear flags.
Detailed Description
System Pmu Header File.
Date
07-July-2017
Version
04.07.00
This file contains:
Pmu Interface Functions
which are relevant for the performance monitor unit driver.
Macro Definition Documentation
pmuCOUNTER0
#define pmuCOUNTER0 0x00000001U
pmu event counter 0 mask
Alias for pmu event counter 0 mask
Note
: Use this macro as a parameter 'counters' in APIs pmuStartCounters and pmuStopCounters
Definition at line 66 of file sys_pmu.h.
pmuCOUNTER1
#define pmuCOUNTER1 0x00000002U
pmu event counter 1 mask
Alias for pmu event counter 1 mask
Note
: Use this macro as a parameter 'counters' in APIs pmuStartCounters and pmuStopCounters
Definition at line 75 of file sys_pmu.h.
pmuCOUNTER2
#define pmuCOUNTER2 0x00000004U
pmu event counter 2 mask
Alias for pmu event counter 2 mask
Note
: Use this macro as a parameter 'counters' in APIs pmuStartCounters and pmuStopCounters
Definition at line 84 of file sys_pmu.h.
pmuCYCLE_COUNTER
#define pmuCYCLE_COUNTER 0x80000000U
pmu cycle counter mask
Alias for pmu event counter mask
Note
: Use this macro as a parameter 'counters' in APIs pmuStartCounters and pmuStopCounters
Definition at line 93 of file sys_pmu.h.
Referenced by errata_PBIST_4().
Enumeration Type Documentation
pmuEvent
enum pmuEvent
pmu event
Alias for pmu event counter increment source
Definition at line 100 of file sys_pmu.h.
{
    PMU_INST_CACHE_MISS = 0x01U,
    PMU_DATA_CACHE_MISS = 0x03U,
    PMU_DATA_CACHE_ACCESS = 0x04U,
    PMU_DATA_READ_ARCH_EXECUTED = 0x06U,
    PMU_DATA_WRITE_ARCH_EXECUTED = 0x07U,
    PMU_INST_ARCH_EXECUTED = 0x08U,
    PMU_EXCEPTION_TAKEN = 0x09U,
    PMU_EXCEPTION_RETURN_ARCH_EXECUTED = 0x0AU,
    PMU_CHANGE_TO_CONTEXT_ID_EXECUTED = 0x0BU,
    PMU_SW_CHANGE_OF_PC_ARCH_EXECUTED = 0x0CU,
    PMU_BRANCH_IMM_INST_ARCH_EXECUTED = 0x0DU,
    PMU_PROC_RETURN_ARCH_EXECUTED = 0x0EU,
    PMU_UNALIGNED_ACCESS_ARCH_EXECUTED = 0x0FU,
    PMU_BRANCH_MISSPREDICTED = 0x10U,
    PMU_CYCLE_COUNT = 0x11U,
    PMU_PREDICTABLE_BRANCHES = 0x12U,
    PMU_INST_BUFFER_STALL = 0x40U,
    PMU_DATA_DEPENDENCY_INST_STALL = 0x41U,
    PMU_DATA_CACHE_WRITE_BACK = 0x42U,
    PMU_EXT_MEMORY_REQUEST = 0x43U,
    PMU_LSU_BUSY_STALL = 0x44U,
    PMU_FORCED_DRAIN_OFSTORE_BUFFER = 0x45U,
    PMU_FIQ_DISABLED_CYCLE_COUNT = 0x46U,
    PMU_IRQ_DISABLED_CYCLE_COUNT = 0x47U,
    PMU_ETMEXTOUT_0 = 0x48U,
    PMU_ETMEXTOUT_1 = 0x49U,
    PMU_INST_CACHE_TAG_ECC_ERROR = 0x4AU,
    PMU_INST_CACHE_DATA_ECC_ERROR = 0x4BU,
    PMU_DATA_CACHE_TAG_ECC_ERROR = 0x4CU,
    PMU_DATA_CACHE_DATA_ECC_ERROR = 0x4DU,
    PMU_TCM_FATAL_ECC_ERROR_PREFETCH = 0x4EU,
    PMU_TCM_FATAL_ECC_ERROR_LOAD_STORE = 0x4FU,
    PMU_STORE_BUFFER_MERGE = 0x50U,
    PMU_LSU_STALL_STORE_BUFFER_FULL = 0x51U,
    PMU_LSU_STALL_STORE_QUEUE_FULL = 0x52U,
    PMU_INTEGER_DIV_EXECUTED = 0x53U,
    PMU_STALL_INTEGER_DIV = 0x54U,
    PMU_PLD_INST_LINE_FILL = 0x55U,
    PMU_PLD_INST_NO_LINE_FILL = 0x56U,
    PMU_NON_CACHEABLE_ACCESS_AXI_MASTER = 0x57U,
    PMU_INST_CACHE_ACCESS = 0x58U,
    PMU_DOUBLE_DATA_CACHE_ISSUE = 0x59U,
    PMU_DUAL_ISSUE_CASE_A = 0x5AU,
    PMU_DUAL_ISSUE_CASE_B1_B2_F2_F2D = 0x5BU,
    PMU_DUAL_ISSUE_OTHER = 0x5CU,
    PMU_DP_FLOAT_INST_EXCECUTED = 0x5DU,
    PMU_DUAL_ISSUED_PAIR_INST_ARCH_EXECUTED = 0x5EU,
    PMU_DATA_CACHE_DATA_FATAL_ECC_ERROR = 0x60U,
    PMU_DATA_CACHE_TAG_FATAL_ECC_ERROR = 0x61U,
    PMU_PROCESSOR_LIVE_LOCK = 0x62U,
    PMU_ATCM_MULTI_BIT_ECC_ERROR = 0x64U,
    PMU_B0TCM_MULTI_BIT_ECC_ERROR = 0x65U,
    PMU_B1TCM_MULTI_BIT_ECC_ERROR = 0x66U,
    PMU_ATCM_SINGLE_BIT_ECC_ERROR = 0x67U,
    PMU_B0TCM_SINGLE_BIT_ECC_ERROR = 0x68U,
    PMU_B1TCM_SINGLE_BIT_ECC_ERROR = 0x69U,
    PMU_TCM_COR_ECC_ERROR_LOAD_STORE = 0x6AU,
    PMU_TCM_COR_ECC_ERROR_PREFETCH = 0x6BU,
    PMU_TCM_FATAL_ECC_ERROR_AXI_SLAVE = 0x6CU,
    PMU_TCM_COR_ECC_ERROR_AXI_SLAVE = 0x6DU
};
Function Documentation
_pmuGetCycleCount_()
uint32 _pmuGetCycleCount_ (void)
Returns current cycle counter value.
Returns
cycle count.
Referenced by errata_PBIST_4().
_pmuGetEventCount_()
uint32 _pmuGetEventCount_ (uint32 counter)
Returns current event counter value.
Parameters
in counter - Counter select 0..2
Returns
event counter count.
_pmuGetOverflow_()
uint32 _pmuGetOverflow_ (void)
Returns current overflow register and clear flags.
Returns
overflow flags.
_pmuSetCountEvent_()
void _pmuSetCountEvent_ (uint32 counter, uint32 event)
Set event counter count event.
Parameters
in counter - Counter select 0..2
in event - Count event
_pmuStartCounters_()
void _pmuStartCounters_ (uint32 counters)
Starts selected counters.
Parameters
in counters - Counter mask
Referenced by errata_PBIST_4().
_pmuStopCounters_()
void _pmuStopCounters_ (uint32 counters)
Stops selected counters.
Parameters
in counters - Counter mask
Referenced by errata_PBIST_4().