generated_launchpad/include/sys_selftest.h File Reference
System Memory Header File.
#include `reg_pbist.h`
#include `reg_stc.h`
#include `reg_efc.h`
#include `sys_core.h`
#include `system.h`
#include `sys_vim.h`
#include `adc.h`
#include `can.h`
#include `mibspi.h`
#include `het.h`
#include `htu.h`
#include `esm.h`
Classes
struct pbist_config_reg
struct stc_config_reg
struct efc_config_reg
struct ccmr4_config_reg
Macros
#define flash1bitError (*(volatile uint32 *)(0xF00803F0U))
#define flash2bitError (*(volatile uint32 *)(0xF00803F8U))
#define tcramA1bitError (*(volatile uint32 *)(0x08400000U))
#define tcramA2bitError (*(volatile uint32 *)(0x08400010U))
#define tcramB1bitError (*(volatile uint32 *)(0x08400008U))
#define tcramB2bitError (*(volatile uint32 *)(0x08400018U))
#define tcramA1bit (*(volatile uint64 *)(0x08000000U))
#define tcramA2bit (*(volatile uint64 *)(0x08000010U))
#define tcramB1bit (*(volatile uint64 *)(0x08000008U))
#define tcramB2bit (*(volatile uint64 *)(0x08000018U))
#define flashBadECC1 (*(volatile uint32 *)(0x20000000U))
#define flashBadECC2 (*(volatile uint32 *)(0x20000010U))
#define CCMSR (*(volatile uint32 *)(0xFFFFF600U))
#define CCMKEYR (*(volatile uint32 *)(0xFFFFF604U))
#define DMA_PARCR (*(volatile uint32 *)(0xFFFFF1A8U))
#define DMA_PARADDR (*(volatile uint32 *)(0xFFFFF1ACU))
#define DMARAMLOC (*(volatile uint32 *)(0xFFF80000U))
#define DMARAMPARLOC (*(volatile uint32 *)(0xFFF80A00U))
#define MIBSPI1RAMLOC (*(volatile uint32 *)(0xFF0E0000U))
#define MIBSPI3RAMLOC (*(volatile uint32 *)(0xFF0C0000U))
#define MIBSPI5RAMLOC (*(volatile uint32 *)(0xFF0A0000U))
#define __PBIST_H__
#define PBIST_ROM_PBIST_RAM_GROUP 1U
#define STC_ROM_PBIST_RAM_GROUP 2U
#define PBIST_RAMT_CONFIGVALUE 0U
#define PBIST_DLR_CONFIGVALUE 0U
#define PBIST_PACT_CONFIGVALUE 0U
#define PBIST_PBISTID_CONFIGVALUE 0U
#define PBIST_OVER_CONFIGVALUE 0U
#define PBIST_FSRDL1_CONFIGVALUE 0U
#define PBIST_ROM_CONFIGVALUE 0U
#define PBIST_ALGO_CONFIGVALUE 0U
#define PBIST_RINFOL_CONFIGVALUE 0U
#define PBIST_RINFOU_CONFIGVALUE 0U
#define __STC_H__
#define STC_INTERVAL 24U
#define STC_MAX_TIMEOUT 0xFFFFFFFFU
#define STC_STCGCR0_CONFIGVALUE 0xFFFF0000U
#define STC_STCGCR1_CONFIGVALUE 0x5U
#define STC_STCTPR_CONFIGVALUE 0xFFFFFFFFU
#define STC_STCSCSCR_CONFIGVALUE 0x5U
#define __EFC_H__
#define INPUT_ENABLE 0x0000000FU
#define INPUT_DISABLE 0x00000000U
#define SYS_WS_READ_STATES 0x00000000U
#define SYS_REPAIR_EN_0 0x00000000U
#define SYS_REPAIR_EN_3 0x00000100U
#define SYS_REPAIR_EN_5 0x00000200U
#define SYS_DEID_AUTOLOAD_EN 0x00000400U
#define EFC_FDI_EN 0x00000800U
#define EFC_FDI_DIS 0x00000000U
#define SYS_ECC_OVERRIDE_EN 0x00001000U
#define SYS_ECC_OVERRIDE_DIS 0x00000000U
#define SYS_ECC_SELF_TEST_EN 0x00002000U
#define SYS_ECC_SELF_TEST_DIS 0x00000000U
#define OUTPUT_ENABLE 0x0003C000U
#define OUTPUT_DISABLE 0x00000000U
#define EFC_AUTOLOAD_ERROR_EN 0x00040000U
#define EFC_INSTRUCTION_ERROR_EN 0x00080000U
#define EFC_INSTRUCTION_INFO_EN 0x00100000U
#define EFC_SELF_TEST_ERROR_EN 0x00200000U
#define EFC_AUTOLOAD_ERROR_DIS 0x00000000U
#define EFC_INSTRUCTION_ERROR_DIS 0x00000000U
#define EFC_INSTRUCTION_INFO_DIS 0x00000000U
#define EFC_SELF_TEST_ERROR_DIS 0x00000000U
#define DISABLE_READ_ROW0 0x00800000U
#define SYS_REPAIR_0 0x00000010U
#define SYS_REPAIR_3 0x00000010U
#define SYS_REPAIR_5 0x00000020U
#define SYS_DEID_AUTOLOAD 0x00000040U
#define SYS_FCLRZ 0x00000080U
#define EFC_READY 0x00000100U
#define SYS_ECC_OVERRIDE 0x00000200U
#define EFC_AUTOLOAD_ERROR 0x00000400U
#define EFC_INSTRUCTION_ERROR 0x00000800U
#define EFC_INSTRUCTION_INFO 0x00001000U
#define SYS_ECC_SELF_TEST 0x00002000U
#define EFC_SELF_TEST_ERROR 0x00004000U
#define EFC_SELF_TEST_DONE 0x00008000U
#define TIME_OUT 0x01
#define AUTOLOAD_NO_FUSEROM_DATA 0x02U
#define AUTOLOAD_SIGN_FAIL 0x03U
#define AUTOLOAD_PROG_INTERRUPT 0x04U
#define AUTOLOAD_TWO_BIT_ERR 0x05U
#define PROGRAME_WR_P_SET 0x06U
#define PROGRAME_MNY_DATA_ITERTN 0x07U
#define PROGRAME_MNY_CNTR_ITERTN 0x08U
#define UN_PROGRAME_BIT_SET 0x09U
#define REDUNDANT_REPAIR_ROW 0x0AU
#define PROGRAME_MNY_CRA_ITERTN 0x0BU
#define PROGRAME_SAME_DATA 0x0CU
#define PROGRAME_CMP_SKIP 0x0DU
#define PROGRAME_ABORT 0x0EU
#define PROGRAME_INCORRECT_KEY 0x0FU
#define FUSEROM_LASTROW_STUCK 0x10U
#define AUTOLOAD_SINGLE_BIT_ERR 0x15U
#define DUMPWORD_TWO_BIT_ERR 0x16U
#define DUMPWORD_ONE_BIT_ERR 0x17U
#define SELF_TEST_ERROR 0x18U
#define INSTRUCTION_DONE 0x20U
#define TEST_UNPROGRAME_ROM 0x01000000U
#define PROGRAME_CRA 0x02000000U
#define DUMP_WORD 0x04000000U
#define LOAD_FUSE_SCAN_CHAIN 0x05000000U
#define PROGRAME_DATA 0x07000000U
#define RUN_AUTOLOAD_8 0x08000000U
#define RUN_AUTOLOAD_A 0x0A000000U
#define EFC_BOUNDARY_CONFIGVALUE 0x0000200FU
#define EFC_PINS_CONFIGVALUE 0x000082E0U
#define EFC_SELFTESTCYCLES_CONFIGVALUE 0x00000258U
#define EFC_SELFTESTSIGN_CONFIGVALUE 0x5362F97FU
#define CCMSELFCHECK_FAIL1 1U
#define CCMSELFCHECK_FAIL2 2U
#define CCMSELFCHECK_FAIL3 3U
#define CCMSELFCHECK_FAIL4 4U
#define PBISTSELFCHECK_FAIL1 5U
#define EFCCHECK_FAIL1 6U
#define EFCCHECK_FAIL2 7U
#define FMCECCCHECK_FAIL1 8U
#define CHECKB0RAMECC_FAIL1 9U
#define CHECKB1RAMECC_FAIL1 10U
#define CHECKFLASHECC_FAIL1 11U
#define VIMPARITYCHECK_FAIL1 12U
#define DMAPARITYCHECK_FAIL1 13U
#define HET1PARITYCHECK_FAIL1 14U
#define HTU1PARITYCHECK_FAIL1 15U
#define HET2PARITYCHECK_FAIL1 16U
#define HTU2PARITYCHECK_FAIL1 17U
#define ADC1PARITYCHECK_FAIL1 18U
#define ADC2PARITYCHECK_FAIL1 19U
#define CAN1PARITYCHECK_FAIL1 20U
#define CAN2PARITYCHECK_FAIL1 21U
#define CAN3PARITYCHECK_FAIL1 22U
#define MIBSPI1PARITYCHECK_FAIL1 23U
#define MIBSPI3PARITYCHECK_FAIL1 24U
#define MIBSPI5PARITYCHECK_FAIL1 25U
#define CHECKRAMECC_FAIL1 26U
#define CHECKRAMECC_FAIL2 27U
#define CHECKCLOCKMONITOR_FAIL1 28U
#define CHECKFLASHEEPROMECC_FAIL1 29U
#define CHECKFLASHEEPROMECC_FAIL2 31U
#define CHECKFLASHEEPROMECC_FAIL3 32U
#define CHECKFLASHEEPROMECC_FAIL4 33U
#define CHECKPLL1SLIP_FAIL1 34U
#define CHECKRAMADDRPARITY_FAIL1 35U
#define CHECKRAMADDRPARITY_FAIL2 36U
#define CHECKRAMUERRTEST_FAIL1 37U
#define CHECKRAMUERRTEST_FAIL2 38U
#define FMCBUS1PARITYCHECK_FAIL1 39U
#define FMCBUS1PARITYCHECK_FAIL2 40U
#define PBISTSELFCHECK_FAIL2 41U
#define PBISTSELFCHECK_FAIL3 42U
#define CCMR4_CCMKEYR_CONFIGVALUE 0U
Typedefs
typedef struct pbist_config_reg pbist_config_reg_t
typedef struct stc_config_reg stc_config_reg_t
typedef struct efc_config_reg efc_config_reg_t
typedef struct ccmr4_config_reg ccmr4_config_reg_t
Enumerations
enum pbistPort { PBIST_PORT0 = 0U,
PBIST_PORT1 = 1U
 }
Alias names for pbist Port number.
enum pbistAlgo {
PBIST_TripleReadSlow = 0x00000001U,
PBIST_TripleReadFast = 0x00000002U,
PBIST_March13N_DP = 0x00000004U,
PBIST_March13N_SP = 0x00000008U,
PBIST_DOWN1a_DP = 0x00000010U,
PBIST_DOWN1a_SP = 0x00000020U,
PBIST_MapColumn_DP = 0x00000040U,
PBIST_MapColumn_SP = 0x00000080U,
PBIST_Precharge_DP = 0x00000100U,
PBIST_Precharge_SP = 0x00000200U,
PBIST_DTXN2a_DP = 0x00000400U,
PBIST_DTXN2a_SP = 0x00000800U,
PBIST_PMOSOpen_DP = 0x00001000U,
PBIST_PMOSOpen_SP = 0x00002000U,
PBIST_PPMOSOpenSlice1_DP = 0x00004000U,
PBIST_PPMOSOpenSlice2_DP = 0x00008000U,
PBIST_Flip10_DP = 0x00010000U,
PBIST_Flip10_SP = 0x00020000U,
PBIST_IDDQ_DP = 0x00040000U,
PBIST_IDDQ_SP = 0x00080000U,
PBIST_Retention_DP = 0x00100000U,
PBIST_Retention_SP = 0x00200000U,
PBIST_IDDQ2_DP = 0x00400000U,
PBIST_IDDQ2_SP = 0x00800000U,
PBIST_Retention2_DP = 0x01000000U,
PBIST_Retention2_SP = 0x02000000U,
PBIST_IDDQRowStripe_DP = 0x04000000U,
PBIST_IDDQRowStripe_SP = 0x08000000U,
PBIST_IDDQRowStripe2_DP = 0x10000000U,
PBIST_IDDQRowStripe2_SP = 0x20000000U
 }
Alias names for pbist Algorithm.
Functions
void memoryPort0TestFailNotification (uint32 groupSelect, uint32 dataSelect, uint32 address, uint32 data)
Memory Port 0 test fail notification.
void memoryPort1TestFailNotification (uint32 groupSelect, uint32 dataSelect, uint32 address, uint32 data)
Memory Port 1 test fail notification.
void pbistGetConfigValue (pbist_config_reg_t *config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
void stcGetConfigValue (stc_config_reg_t *config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
void efcGetConfigValue (efc_config_reg_t *config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
void ccmSelfCheck (void)
CCM module self check Driver.
void stcSelfCheck (void)
STC module self check Driver.
void stcSelfCheckFail (void)
STC Self test check fail service routine.
void cpuSelfTest (uint32 no_of_intervals, uint32 max_timeout, boolean restart_test)
CPU self test Driver.
void cpuSelfTestFail (void)
CPU Self test check fail service routine.
void memoryInit (uint32 ram)
Memory Initialization Driver.
void pbistSelfCheck (void)
PBIST self test Driver.
void pbistRun (uint32 raminfoL, uint32 algomask)
CPU self test Driver.
void pbistStop (void)
Routine to stop PBIST test enabled.
boolean pbistIsTestCompleted (void)
Checks to see if the PBIST test is completed.
boolean pbistIsTestPassed (void)
Checks to see if the PBIST test is completed successfully.
boolean pbistPortTestStatus (uint32 port)
Checks to see if the PBIST Port test is completed successfully.
void pbistFail (void)
uint32 efcCheck (void)
EFUSE module self check Driver.
void efcSelfTest (void)
EFUSE module self check Driver.
boolean efcStuckZeroTest (void)
Checks to see if the EFUSE Stuck at zero test is completed successfully.
boolean checkefcSelfTest (void)
EFUSE module self check Driver.
void fmcBus2Check (void)
Self Check Flash Bus2 Interface.
void fmcECCcheck (void)
Check Flash ECC Single Bit and multi Bit errors detection logic.
void fmcBus1ParityCheck (void)
void checkB0RAMECC (void)
Check TCRAM1 ECC error detection logic.
void checkB1RAMECC (void)
Check TCRAM2 ECC error detection logic.
void checkFlashECC (void)
Check Flash ECC error detection logic.
void vimParityCheck (void)
Routine to check VIM RAM parity error detection and signaling mechanism.
void dmaParityCheck (void)
Routine to check DMA control packet RAM parity error detection and signaling mechanism.
void adc1ParityCheck (void)
Routine to check ADC1 RAM parity error detection and signaling mechanism.
void adc2ParityCheck (void)
Routine to check ADC2 RAM parity error detection and signaling mechanism.
void het1ParityCheck (void)
Routine to check HET1 RAM parity error detection and signaling mechanism.
void htu1ParityCheck (void)
Routine to check HTU1 RAM parity error detection and signaling mechanism.
void het2ParityCheck (void)
Routine to check HET2 RAM parity error detection and signaling mechanism.
void htu2ParityCheck (void)
Routine to check HTU2 RAM parity error detection and signaling mechanism.
void can1ParityCheck (void)
Routine to check CAN1 RAM parity error detection and signaling mechanism.
void can2ParityCheck (void)
Routine to check CAN2 RAM parity error detection and signaling mechanism.
void can3ParityCheck (void)
Routine to check CAN3 RAM parity error detection and signaling mechanism.
void mibspi1ParityCheck (void)
Routine to check MIBSPI1 RAM parity error detection and signaling mechanism.
void mibspi3ParityCheck (void)
Routine to check MIBSPI3 RAM parity error detection and signaling mechanism.
void mibspi5ParityCheck (void)
Routine to check MIBSPI5 RAM parity error detection and signaling mechanism.
void checkRAMECC (void)
Check TCRAM ECC error detection logic.
void checkClockMonitor (void)
Check clock monitor failure detection logic.
void checkFlashEEPROMECC (void)
Check Flash EEPROM ECC error detection logic.
void checkPLL1Slip (void)
Check PLL1 Slip detection logic.
void checkPLL2Slip (void)
Check PLL2 Slip detection logic.
void checkRAMAddrParity (void)
Check TCRAM Address parity error detection and signaling mechanism.
void checkRAMUERRTest (void)
Run RAM test.
void enableParity (void)
Enable peripheral RAM parity.
void disableParity (void)
Disable peripheral RAM parity.
void custom_dabort (void)
Custom Data abort routine for the application.
void selftestFailNotification (uint32 flag)
Self test fail service routine.
void errata_PBIST_4 (void)
Workaround for the Errata PBIST#4.
void ccmr4GetConfigValue (ccmr4_config_reg_t *config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
Detailed Description
System Memory Header File.
Date
07-July-2017
Version
04.07.00
This file contains:
Efuse Self Test Functions
which are relevant for the System driver.
Enumeration Type Documentation
pbistAlgo
enum pbistAlgo
Alias names for pbist Algorithm.
This enumeration is used to provide alias names for the pbist Algorithm
Enumerator
PBIST_TripleReadSlow TRIPLE_READ_SLOW_READ for PBIST and STC ROM
PBIST_TripleReadFast TRIPLE_READ_SLOW_READ for PBIST and STC ROM
PBIST_March13N_DP March13 N Algo for 2 Port mem
PBIST_March13N_SP March13 N Algo for 1 Port mem
PBIST_DOWN1a_DP Down1a Algor forces the switching fo all data bits & most addr bits on consecutive read cycles
PBIST_DOWN1a_SP Down1a Algor forces the switching fo all data bits & most addr bits on consecutive read cycles
PBIST_MapColumn_DP Map Column algo (to identify bit line senstivities) for 2 Port memory
PBIST_MapColumn_SP Map Column algo (to identify bit line senstivities) for 1 Port memory
PBIST_Precharge_DP Pre-Charge algo to exercise pre-charge capability for 2 port memory
PBIST_Precharge_SP Pre-Charge algo to exercise pre-charge capability for 1 port memory
PBIST_DTXN2a_DP Global column decode logic algo for 2 Port memories
PBIST_DTXN2a_SP Global column decode logic algo for 1 Port memories
PBIST_PMOSOpen_DP pmos oper algo for 2 port memories
PBIST_PMOSOpen_SP pmos oper algo for 1 port memories
PBIST_PPMOSOpenSlice1_DP pmos open slice1 for 2port memories
PBIST_PPMOSOpenSlice2_DP pmos open slice2 for 2port memories
PBIST_Flip10_DP flip10 algo for 2 port memories
PBIST_Flip10_SP flip10 algo for 1 port memories
PBIST_IDDQ_DP iddq algo for 2 port memories
PBIST_IDDQ_SP iddq algo for 1 port memories
PBIST_Retention_DP retention algo for 2 port memories
PBIST_Retention_SP retention algo for 1 port memories
PBIST_IDDQ2_DP iddq2 algo for 2 port memories
PBIST_IDDQ2_SP iddq2 algo for 1 port memories
PBIST_Retention2_DP retention2 algo for 2 port memories
PBIST_Retention2_SP retention2 algo for 1 port memories
PBIST_IDDQRowStripe_DP iddqwstripe algo for 2 port memories
PBIST_IDDQRowStripe_SP iddqwstripe algo for 1 port memories
PBIST_IDDQRowStripe2_DP iddqwstripe2 algo for 2 port memories
PBIST_IDDQRowStripe2_SP iddqwstripe2 algo for 1 port memories
Definition at line 119 of file sys_selftest.h.
{
    PBIST_TripleReadSlow = 0x00000001U,
    PBIST_TripleReadFast = 0x00000002U,
    PBIST_March13N_DP = 0x00000004U,
    PBIST_March13N_SP = 0x00000008U,
    PBIST_DOWN1a_DP = 0x00000010U,
    PBIST_DOWN1a_SP = 0x00000020U,
    PBIST_MapColumn_DP = 0x00000040U,
    PBIST_MapColumn_SP = 0x00000080U,
    PBIST_Precharge_DP = 0x00000100U,
    PBIST_Precharge_SP = 0x00000200U,
    PBIST_DTXN2a_DP = 0x00000400U,
    PBIST_DTXN2a_SP = 0x00000800U,
    PBIST_PMOSOpen_DP = 0x00001000U,
    PBIST_PMOSOpen_SP = 0x00002000U,
    PBIST_PPMOSOpenSlice1_DP = 0x00004000U,
    PBIST_PPMOSOpenSlice2_DP = 0x00008000U,
    PBIST_Flip10_DP = 0x00010000U,
    PBIST_Flip10_SP = 0x00020000U,
    PBIST_IDDQ_DP = 0x00040000U,
    PBIST_IDDQ_SP = 0x00080000U,
    PBIST_Retention_DP = 0x00100000U,
    PBIST_Retention_SP = 0x00200000U,
    PBIST_IDDQ2_DP = 0x00400000U,
    PBIST_IDDQ2_SP = 0x00800000U,
    PBIST_Retention2_DP = 0x01000000U,
    PBIST_Retention2_SP = 0x02000000U,
    PBIST_IDDQRowStripe_DP = 0x04000000U,
    PBIST_IDDQRowStripe_SP = 0x08000000U,
    PBIST_IDDQRowStripe2_DP = 0x10000000U,
    PBIST_IDDQRowStripe2_SP = 0x20000000U
};
pbistPort
enum pbistPort
Alias names for pbist Port number.
This enumeration is used to provide alias names for the pbist Port number
PBIST_PORT0
PBIST_PORT1
Note
Check the datasheet for the port avaiability
Enumerator
PBIST_PORT0 Alias for PBIST Port 0
PBIST_PORT1 Alias for PBIST Port 1 < Check datasheet for Port 1 availability >
Definition at line 109 of file sys_selftest.h.
{
    PBIST_PORT0 = 0U,
    PBIST_PORT1 = 1U
};
Function Documentation
adc1ParityCheck()
void adc1ParityCheck (void)
Routine to check ADC1 RAM parity error detection and signaling mechanism.
Routine to check ADC1 RAM parity error detection and signaling mechanism
Definition at line 1526 of file sys_selftest.c.
References adcPARRAM1, adcRAM1, adcREG1, esmREG, and selftestFailNotification().
{
    volatile uint32 adcramread = 0U;
    uint32 adcparcr_bk = adcREG1->PARCR;
/* USER CODE BEGIN (61) */
/* USER CODE END */
    /* Set the TEST bit in the PARCR and enable parity checking */
    adcREG1->PARCR = 0x10AU;
    /* Invert the parity bits inside the ADC1 RAM's first location */
    adcPARRAM1 = ~(adcPARRAM1);
    /* clear the TEST bit */
    adcREG1->PARCR = 0x00AU;
    /* This read is expected to trigger a parity error */
    adcramread = adcRAM1;
    /* Check for ESM group1 channel 19 to be flagged */
    if ((esmREG->SR1[0U] & 0x80000U) ==0U)
    {
        /* no ADC1 RAM parity error was flagged to ESM */
        selftestFailNotification(ADC1PARITYCHECK_FAIL1);
    }
    else
    {
        /* clear ADC1 RAM parity error flag */
        esmREG->SR1[0U] = 0x80000U;
        /* Set the TEST bit in the PARCR and enable parity checking */
        adcREG1->PARCR = 0x10AU;
        /* Revert back the parity bits to correct data */
        adcPARRAM1 = ~(adcPARRAM1);
    }
    /* Restore parity control register */
    adcREG1->PARCR = adcparcr_bk;
/* USER CODE BEGIN (62) */
/* USER CODE END */
}
adc2ParityCheck()
void adc2ParityCheck (void)
Routine to check ADC2 RAM parity error detection and signaling mechanism.
Routine to check ADC2 RAM parity error detection and signaling mechanism
Definition at line 1580 of file sys_selftest.c.
References adcPARRAM2, adcRAM2, adcREG2, esmREG, and selftestFailNotification().
{
    volatile uint32 adcramread = 0U;
    uint32 adcparcr_bk = adcREG2->PARCR;
/* USER CODE BEGIN (63) */
/* USER CODE END */
    /* Set the TEST bit in the PARCR and enable parity checking */
    adcREG2->PARCR = 0x10AU;
    /* Invert the parity bits inside the ADC2 RAM's first location */
    adcPARRAM2 = ~(adcPARRAM2);
    /* clear the TEST bit */
    adcREG2->PARCR = 0x00AU;
    /* This read is expected to trigger a parity error */
    adcramread = adcRAM2;
    /* Check for ESM group1 channel 1 to be flagged */
    if ((esmREG->SR1[0U] & 0x2U) == 0U)
    {
        /* no ADC2 RAM parity error was flagged to ESM */
        selftestFailNotification(ADC2PARITYCHECK_FAIL1);
    }
    else
    {
        /* clear ADC2 RAM parity error flag */
        esmREG->SR1[0U] = 0x2U;
        /* Set the TEST bit in the PARCR and enable parity checking */
        adcREG2->PARCR = 0x10AU;
        /* Revert back the parity bits to correct data */
        adcPARRAM2 = ~(adcPARRAM2);
    }
    /* Restore parity control register*/
    adcREG2->PARCR = adcparcr_bk;
/* USER CODE BEGIN (64) */
/* USER CODE END */
}
can1ParityCheck()
void can1ParityCheck (void)
Routine to check CAN1 RAM parity error detection and signaling mechanism.
Routine to check CAN1 RAM parity error detection and signaling mechanism
Definition at line 1633 of file sys_selftest.c.
References canPARRAM1, canRAM1, canREG1, esmREG, and selftestFailNotification().
{
    volatile uint32 canread = 0U;
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "LDRA Tool issue" */
    uint32 canctl_bk = canREG1->CTL;
/* USER CODE BEGIN (65) */
/* USER CODE END */
    /* Disable parity, init mode, TEST mode */
    canREG1->CTL = 0x00001481U;
    /* Enable RAM Direct Access mode */
    canREG1->TEST = 0x00000200U;
    /* flip the parity bit */
    canPARRAM1 ^= 0x00001000U;
    /* Enable parity, disable init, still TEST mode */
    canREG1->CTL = 0x00002880U;
    /* Read location with parity error */
    canread = canRAM1;
    /* check if ESM group1 channel 21 is flagged */
    if ((esmREG->SR1[0U] & 0x00200000U) == 0U)
    {
        /* No DCAN1 RAM parity error was flagged to ESM */
        selftestFailNotification(CAN1PARITYCHECK_FAIL1);
    }
    else
    {
        /* clear ESM group1 channel 21 flag */
        esmREG->SR1[0U] = 0x00200000U;
        /* Disable parity, init mode, TEST mode */
        canREG1->CTL = 0x00001481U;
        /* Revert back to correct data, flip bit 0 of the parity location */
        canPARRAM1 ^= 0x00001000U;
    }
    /* Disable RAM Direct Access mode */
    canREG1->TEST = 0x00000000U;
    /* Restore CTL register */
    canREG1->CTL = canctl_bk;
    /* Read Error and Status register to clear Parity Error bit */
    canread = canREG1->ES;
/* USER CODE BEGIN (66) */
/* USER CODE END */
}
can2ParityCheck()
void can2ParityCheck (void)
Routine to check CAN2 RAM parity error detection and signaling mechanism.
Routine to check CAN2 RAM parity error detection and signaling mechanism
Definition at line 1697 of file sys_selftest.c.
References canPARRAM2, canRAM2, canREG2, esmREG, and selftestFailNotification().
{
    volatile uint32 canread = 0U;
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "LDRA Tool issue" */
    uint32 canctl_bk = canREG2->CTL;
/* USER CODE BEGIN (67) */
/* USER CODE END */
    /* Disable parity, init mode, TEST mode */
    canREG2->CTL = 0x00001481U;
    /* Enable RAM Direct Access mode */
    canREG2->TEST = 0x00000200U;
    /* flip the parity bit */
    canPARRAM2 ^= 0x00001000U;
    /* Enable parity, disable init, still TEST mode */
    canREG2->CTL = 0x00002880U;
    /* Read location with parity error */
    canread = canRAM2;
    /* check if ESM group1 channel 23 is flagged */
    if ((esmREG->SR1[0U] & 0x00800000U) == 0U)
    {
        /* No DCAN2 RAM parity error was flagged to ESM */
        selftestFailNotification(CAN2PARITYCHECK_FAIL1);
    }
    else
    {
        /* clear ESM group1 channel 23 flag */
        esmREG->SR1[0U] = 0x00800000U;
        /* Disable parity, init mode, TEST mode */
        canREG2->CTL = 0x00001481U;
        /* Revert back to correct data, flip bit 0 of the parity location */
        canPARRAM2 ^= 0x00001000U;
    }
    /* Disable RAM Direct Access mode */
    canREG2->TEST = 0x00000000U;
    /* disable TEST mode */
    canREG2->CTL = canctl_bk;
    /* Read Error and Status register to clear Parity Error bit */
    canread = canREG2->ES;
/* USER CODE BEGIN (68) */
/* USER CODE END */
}
can3ParityCheck()
void can3ParityCheck (void)
Routine to check CAN3 RAM parity error detection and signaling mechanism.
Routine to check CAN3 RAM parity error detection and signaling mechanism
Definition at line 1761 of file sys_selftest.c.
References canPARRAM3, canRAM3, canREG3, esmREG, and selftestFailNotification().
{
    volatile uint32 canread = 0U;
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "LDRA Tool issue" */
    uint32 canctl_bk = canREG3->CTL;
/* USER CODE BEGIN (69) */
/* USER CODE END */
    /* Disable parity, init mode, TEST mode */
    canREG3->CTL = 0x00001481U;
    /* Enable RAM Direct Access mode */
    canREG3->TEST = 0x00000200U;
    /* flip the parity bit */
    canPARRAM3 ^= 0x00001000U;
    /* Enable parity, disable init, still TEST mode */
    canREG3->CTL = 0x00002880U;
    /* Read location with parity error */
    canread = canRAM3;
    /* check if ESM group1 channel 22 is flagged */
    if ((esmREG->SR1[0U] & 0x00400000U) == 0U)
    {
        /* No DCAN3 RAM parity error was flagged to ESM */
        selftestFailNotification(CAN3PARITYCHECK_FAIL1);
    }
    else
    {
        /* clear ESM group1 channel 22 flag */
        esmREG->SR1[0U] = 0x00400000U;
        /* Disable parity, init mode, TEST mode */
        canREG3->CTL = 0x00001481U;
        /* Revert back to correct data, flip bit 0 of the parity location */
        canPARRAM3 ^= 0x00001000U;
    }
    /* Disable RAM Direct Access mode */
    canREG3->TEST = 0x00000000U;
    /* disable TEST mode */
    canREG3->CTL = canctl_bk;
    /* Read Error and Status register to clear Parity Error bit */
    canread = canREG3->ES;
/* USER CODE BEGIN (70) */
/* USER CODE END */
}
ccmr4GetConfigValue()
void ccmr4GetConfigValue (ccmr4_config_reg_t * config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
Parameters
in *config_reg pointer to the struct to which the initial or current value of the configuration registers need to be stored
in type whether initial or current value of the configuration registers need to be stored
InitialValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
CurrentValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
This function will copy the initial or current value (depending on the parameter 'type') of the configuration registers to the struct pointed by config_reg
Definition at line 2759 of file sys_selftest.c.
{
    if (type == InitialValue)
    {
        config_reg->CONFIG_CCMKEYR = CCMR4_CCMKEYR_CONFIGVALUE;
    }
    else
    {
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "LDRA Tool issue" */
        config_reg->CONFIG_CCMKEYR = CCMKEYR;
    }
}
ccmSelfCheck()
void ccmSelfCheck (void)
CCM module self check Driver.
This function self checks the CCM module.
Definition at line 77 of file sys_selftest.c.
{
/* USER CODE BEGIN (3) */
/* USER CODE END */
    /* Run a diagnostic check on the CCM-R4F module */
    /* This step ensures that the CCM-R4F can actually indicate an error */
    /* Configure CCM in self-test mode */
    CCMKEYR = 0x6U;
    /* Wait for CCM self-test to complete */
    /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
    while ((CCMSR & 0x100U) != 0x100U)
    {
    }/* Wait */
/* USER CODE BEGIN (4) */
/* USER CODE END */
    /* Check if there was an error during the self-test */
    if ((CCMSR & 0x1U) == 0x1U)
    {
        /* STE is set */
        selftestFailNotification(CCMSELFCHECK_FAIL1);
    }
    else
    {
        /* Check CCM-R4 self-test error flag by itself (without compare error) */
        if ((esmREG->SR1[0U] & 0x80000000U) == 0x80000000U)
        {
            /* ESM flag is not set */
            selftestFailNotification(CCMSELFCHECK_FAIL2);
        }
        else
        {
            /* Configure CCM in error-forcing mode */
            CCMKEYR = 0x9U;
            /* Wait till error-forcing is completed. */
            /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
            while (CCMKEYR != 0U)
            {
            }/* Wait */
            /* check if compare error flag is set */
            if ((esmREG->SR1[1U] & 0x4U) != 0x4U)
            {
                /* ESM flag is not set */
                selftestFailNotification(CCMSELFCHECK_FAIL3);
            }
            else
            {
                /* Check FIQIVEC to ESM High Interrupt flag is set */
                if((vimREG->FIQINDEX & 0x000000FFU) != 1U)
                {
                   /* ESM High Interrupt flag is not set in VIM*/
                   selftestFailNotification(CCMSELFCHECK_FAIL4);
                }
                /* clear ESM group2 channel 2 flag */
                esmREG->SR1[1U] = 0x4U;
                /* clear ESM group2 shadow status flag */
                esmREG->SSR2 = 0x4U;
                /* ESM self-test error needs to also be cleared */
                esmREG->SR1[0U] = 0x80000000U;
                /* The nERROR pin will become inactive once the LTC counter expires */
                esmREG->EKR = 0x5U;
                /* Configure CCM in selftest error-forcing mode */
                CCMKEYR = 0xFU;
                /* Wait till selftest error-forcing is completed. */
                /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
                while (CCMKEYR != 0U)
                {
                }/* Wait */
                if((esmREG->SR1[0U] & 0x80000000U) != 0x80000000U)
                {
                    /* ESM flag not set */
                    selftestFailNotification(CCMSELFCHECK_FAIL2);
                }
                else
                {
                    /* clear ESM flag */
                    esmREG->SR1[0U] = 0x80000000U;
                }
            }
        }
    }
}
checkB0RAMECC()
void checkB0RAMECC (void)
Check TCRAM1 ECC error detection logic.
This function checks TCRAM1 ECC error detection logic.
Definition at line 851 of file sys_selftest.c.
{
    volatile uint64 ramread = 0U;
    volatile uint32 regread = 0U;
    uint32 tcram1ErrStat, tcram2ErrStat = 0U;
    
    uint64 tcramA1_bk = tcramA1bit;
    uint64 tcramA2_bk = tcramA2bit;
    volatile uint32 i;
/* USER CODE BEGIN (36) */
/* USER CODE END */
    /* enable writes to ECC RAM, enable ECC error response */
    tcram1REG->RAMCTRL = 0x0005010AU;
    tcram2REG->RAMCTRL = 0x0005010AU;
    /* the first 1-bit error will cause an error response */
    tcram1REG->RAMTHRESHOLD = 0x1U;
    tcram2REG->RAMTHRESHOLD = 0x1U;
    /* allow SERR to be reported to ESM */
    tcram1REG->RAMINTCTRL = 0x1U;
    tcram2REG->RAMINTCTRL = 0x1U;
    /* cause a 1-bit ECC error */
    _coreDisableRamEcc_();
    tcramA1bitError ^= 0x1U;
    _coreEnableRamEcc_();
    /* disable writes to ECC RAM */
    tcram1REG->RAMCTRL = 0x0005000AU;
    tcram2REG->RAMCTRL = 0x0005000AU;
    /* read from location with 1-bit ECC error */
    ramread = tcramA1bit;
    /* Check for error status */
    tcram1ErrStat = tcram1REG->RAMERRSTATUS & 0x1U;
    tcram2ErrStat = tcram2REG->RAMERRSTATUS & 0x1U;
    /*SAFETYMCUSW 139 S MR:13.7 <APPROVED> "LDRA Tool issue" */
    /*SAFETYMCUSW 139 S MR:13.7 <APPROVED> "LDRA Tool issue" */
    if((tcram1ErrStat == 0U) && (tcram2ErrStat == 0U))
    {
        /* TCRAM module does not reflect 1-bit error reported by CPU */
        selftestFailNotification(CHECKB0RAMECC_FAIL1);
    }
    else
    {
        /* clear SERR flag */
        tcram1REG->RAMERRSTATUS = 0x1U;
        tcram2REG->RAMERRSTATUS = 0x1U;
        /* clear status flags for ESM group1 channels 26 and 28 */
        esmREG->SR1[0U] = 0x14000000U;
    }
    /* enable writes to ECC RAM, enable ECC error response */
    tcram1REG->RAMCTRL = 0x0005010AU;
    tcram2REG->RAMCTRL = 0x0005010AU;
    /* cause a 2-bit ECC error */
    _coreDisableRamEcc_();
    tcramA2bitError ^= 0x3U;
    _coreEnableRamEcc_();
    /* read from location with 2-bit ECC error this will cause a data abort to be generated */
    ramread = tcramA2bit;
    /* delay before restoring the ram value */
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
    for(i=0U;i<10U;i++)
    {
    }/* Wait */
    regread = tcram1REG->RAMUERRADDR;
    regread = tcram2REG->RAMUERRADDR;
    /* disable writes to ECC RAM */
    tcram1REG->RAMCTRL = 0x0005000AU;
    tcram2REG->RAMCTRL = 0x0005000AU;
    /* Compute correct ECC */
    tcramA1bit = tcramA1_bk;
    tcramA2bit = tcramA2_bk;
/* USER CODE BEGIN (37) */
/* USER CODE END */
}
checkB1RAMECC()
void checkB1RAMECC (void)
Check TCRAM2 ECC error detection logic.
This function checks TCRAM2 ECC error detection logic.
Definition at line 949 of file sys_selftest.c.
{
    volatile uint64 ramread = 0U;
    volatile uint32 regread = 0U;
    uint32 tcram1ErrStat, tcram2ErrStat = 0U;
    uint64 tcramB1_bk = tcramB1bit;
    uint64 tcramB2_bk = tcramB2bit;
    volatile uint32 i;
/* USER CODE BEGIN (38) */
/* USER CODE END */
    /* enable writes to ECC RAM, enable ECC error response */
    tcram1REG->RAMCTRL = 0x0005010AU;
    tcram2REG->RAMCTRL = 0x0005010AU;
    /* the first 1-bit error will cause an error response */
    tcram1REG->RAMTHRESHOLD = 0x1U;
    tcram2REG->RAMTHRESHOLD = 0x1U;
    /* allow SERR to be reported to ESM */
    tcram1REG->RAMINTCTRL = 0x1U;
    tcram2REG->RAMINTCTRL = 0x1U;
    /* cause a 1-bit ECC error */
    _coreDisableRamEcc_();
    tcramB1bitError ^= 0x1U;
    _coreEnableRamEcc_();
    /* disable writes to ECC RAM */
    tcram1REG->RAMCTRL = 0x0005000AU;
    tcram2REG->RAMCTRL = 0x0005000AU;
    /* read from location with 1-bit ECC error */
    ramread = tcramB1bit;
    /* Check for error status */
    tcram1ErrStat = tcram1REG->RAMERRSTATUS & 0x1U;
    tcram2ErrStat = tcram2REG->RAMERRSTATUS & 0x1U;
    /*SAFETYMCUSW 139 S MR:13.7 <APPROVED> "LDRA Tool issue" */
    /*SAFETYMCUSW 139 S MR:13.7 <APPROVED> "LDRA Tool issue" */
    if((tcram1ErrStat == 0U) && (tcram2ErrStat == 0U))
    {
        /* TCRAM module does not reflect 1-bit error reported by CPU */
        selftestFailNotification(CHECKB1RAMECC_FAIL1);
    }
    else
    {
        /* clear SERR flag */
        tcram1REG->RAMERRSTATUS = 0x1U;
        tcram2REG->RAMERRSTATUS = 0x1U;
        /* clear status flags for ESM group1 channels 26 and 28 */
        esmREG->SR1[0U] = 0x14000000U;
    }
    /* enable writes to ECC RAM, enable ECC error response */
    tcram1REG->RAMCTRL = 0x0005010AU;
    tcram2REG->RAMCTRL = 0x0005010AU;
    /* cause a 2-bit ECC error */
    _coreDisableRamEcc_();
    tcramB2bitError ^= 0x3U;
    _coreEnableRamEcc_();
    /* read from location with 2-bit ECC error this will cause a data abort to be generated */
    ramread = tcramB2bit;
    /* delay before restoring the ram value */
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
    for(i=0U;i<10U;i++)
    {
    }/* Wait */
    regread = tcram1REG->RAMUERRADDR;
    regread = tcram2REG->RAMUERRADDR;
    /* disable writes to ECC RAM */
    tcram1REG->RAMCTRL = 0x0005000AU;
    tcram2REG->RAMCTRL = 0x0005000AU;
    /* Compute correct ECC */
    tcramB1bit = tcramB1_bk;
    tcramB2bit = tcramB2_bk;
/* USER CODE BEGIN (39) */
/* USER CODE END */
}
checkClockMonitor()
void checkClockMonitor (void)
Check clock monitor failure detection logic.
This function checks clock monitor failure detection logic.
Definition at line 2114 of file sys_selftest.c.
References esmREG, selftestFailNotification(), and systemREG1.
{
    uint32 ghvsrc_bk;
    /* Enable clock monitor range detection circuitry */
    systemREG1->CLKTEST |= 0x03000000U;
    /* Backup register GHVSRC */
    ghvsrc_bk = systemREG1->GHVSRC;
    /* Switch all clock domains to HF LPO */
    systemREG1->GHVSRC = 0x05050005U;
    /* Disable oscillator to cause a oscillator fail */
    systemREG1->CSDISSET = 0x1U;
    /* Wait till oscillator fail flag is set */
    /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
    while((systemREG1->GBLSTAT & 0x1U) == 0U)
    {
    } /* Wait */
    if((esmREG->SR1[0U] & 0x800U) != 0x800U)
    {
        selftestFailNotification(CHECKCLOCKMONITOR_FAIL1);
    }
    else
    {
        /* Clear ESM flag */
        esmREG->SR1[0U] = 0x800U;
        /* Disable clock monitor range detection circuitry */
        systemREG1->CLKTEST &= ~(0x03000000U);
        /* Enable oscillator */
        systemREG1->CSDISCLR = 0x1U;
        /* Wait until oscillator is enabled */
        /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
        while((systemREG1->CSVSTAT & 0x3U) == 0U)
        {
        } /* Wait */
        /* Clear oscillator fail flag and PLL slip flag if any*/
        systemREG1->GBLSTAT = 0x301U;
        /* Switch back all clock domains */
        systemREG1->GHVSRC = ghvsrc_bk;
    }
}
checkefcSelfTest()
boolean checkefcSelfTest (void)
EFUSE module self check Driver.
Returns
Returns TRUE if EFC Selftest was a PASS, else FALSE
This function returns the status of efcSelfTest. Note: This function can be called only after calling efcSelfTest
Definition at line 721 of file sys_selftest.c.
References FALSE.
Referenced by systemInit().
{
/* USER CODE BEGIN (31) */
/* USER CODE END */
    boolean result = FALSE;
    uint32 EFC_PINS, EFC_ERROR;
    uint32 esmCh40Stat, esmCh41Stat = 0U;
    /* wait until EFC self-test is done */
    /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
    while((efcREG->PINS & EFC_SELF_TEST_DONE) == 0U)
    {
    }/* Wait */
    /* check if EFC self-test error occurred */
    EFC_PINS = efcREG->PINS;
    EFC_ERROR = efcREG->ERROR;
    if(((EFC_PINS & EFC_SELF_TEST_ERROR) == 0U) && ((EFC_ERROR & 0x1FU) == 0U))
    {
        /* check if EFC self-test error is set */
        esmCh40Stat = esmREG->SR4[0U] & 0x100U;
        esmCh41Stat = esmREG->SR4[0U] & 0x200U;
        if ((esmCh40Stat == 0U) && (esmCh41Stat == 0U))
        {
            result = TRUE;
        }
    }
    return result;
}
checkFlashECC()
void checkFlashECC (void)
Check Flash ECC error detection logic.
This function checks Flash ECC error detection logic.
Definition at line 1047 of file sys_selftest.c.
References flashWREG.
{
    /* Routine to check operation of ECC logic inside CPU for accesses to program flash */
    volatile uint32 flashread = 0U;
/* USER CODE BEGIN (40) */
/* USER CODE END */
    /* Flash Module ECC Response enabled */
    flashWREG->FEDACCTRL1 = 0x000A060AU;
    /* Enable diagnostic mode and select diag mode 7 */
    flashWREG->FDIAGCTRL = 0x00050007U;
    /* Select ECC diagnostic mode, single-bit to be corrupted */
    flashWREG->FPAROVR = 0x00005A01U;
    /* Set the trigger for the diagnostic mode */
    flashWREG->FDIAGCTRL |= 0x01000000U;
    /* read a flash location from the mirrored memory map */
    flashread = flashBadECC1;
    /* disable diagnostic mode */
    flashWREG->FDIAGCTRL = 0x000A0007U;
    /* this will have caused a single-bit error to be generated and corrected by CPU */
    /* single-bit error not captured in flash module */
    /*SAFETYMCUSW 139 S MR:13.7 <APPROVED> "Hardware status bit read check" */
    if ((flashWREG->FEDACSTATUS & 0x2U) == 0U)
    {
        selftestFailNotification(CHECKFLASHECC_FAIL1);
    }
    else
    {
        /* clear single-bit error flag */
        flashWREG->FEDACSTATUS = 0x2U;
        /* clear ESM flag */
        esmREG->SR1[0U] = 0x40U;
        /* Enable diagnostic mode and select diag mode 7 */
        flashWREG->FDIAGCTRL = 0x00050007U;
        /* Select ECC diagnostic mode, two bits of ECC to be corrupted */
        flashWREG->FPAROVR = 0x00005A03U;
        /* Set the trigger for the diagnostic mode */
        flashWREG->FDIAGCTRL |= 0x01000000U;
        /* read from flash location from mirrored memory map this will cause a data abort */
        flashread = flashBadECC2;
        /* Read FUNCERRADD register */
        flashread = flashWREG->FUNCERRADD;
        /* disable diagnostic mode */
        flashWREG->FDIAGCTRL = 0x000A0007U;
    }
/* USER CODE BEGIN (41) */
/* USER CODE END */
}
checkFlashEEPROMECC()
void checkFlashEEPROMECC (void)
Check Flash EEPROM ECC error detection logic.
This function checks Flash EEPROM ECC error detection logic.
Definition at line 2173 of file sys_selftest.c.
References flashWREG, and selftestFailNotification().
{
    uint32 ecc;
    volatile uint32 regread;
    /* Set Single Error Correction Threshold as 1 */
    flashWREG->EECTRL2 |= 1U;
    /* Enable EEPROM Emulation Error Profiling */
    flashWREG->EECTRL1 |= 0x00000100U;
    /* Load FEMU_XX regs in order to generate ECC */
    flashWREG->FEMUADDR = 0xF0200000U;
    flashWREG->FEMUDMSW = 0U;
    flashWREG->FEMUDLSW = 0U;
    /* ECC for the correct data*/
    ecc = flashWREG->FEMUECC;
    /* Load data with 1 bit error */
    flashWREG->FEMUDMSW = 0U;
    flashWREG->FEMUDLSW = 1U;
    /* Enable Diagnostic ECC data correction mode and select FEE SECDED for diagnostic testing */
    flashWREG->FDIAGCTRL = 0x00055001U;
    flashWREG->FEMUECC = ecc;
    /* Diagnostic trigger */
    flashWREG->FDIAGCTRL |= 0x01000000U;
    /*SAFETYMCUSW 139 S MR:13.7 <APPROVED> "Hardware status bit read check" */
    if((flashWREG->EESTATUS & 0x1U) != 0x1U)
    {
        /* No single bit error was detected */
        selftestFailNotification(CHECKFLASHEEPROMECC_FAIL1);
    }
    else
    {
        if((esmREG->SR4[0U] & 0x8U) != 0x8U)
        {
            /* EEPROM single bit error not captured in ESM */
            selftestFailNotification(CHECKFLASHEEPROMECC_FAIL2);
        }
        else
        {
            /* Clear single bit error flag in flash wrapper */
            flashWREG->EESTATUS = 0xFU;
            /* Clear ESM flag */
            esmREG->SR4[0U] = 0x8U;
        }
    }
    /* Load data with 2 bit error */
    flashWREG->FEMUDMSW = 0U;
    flashWREG->FEMUDLSW = 3U;
    /* Enable Diagnostic ECC data correction mode and select FEE SECDED for diagnostic testing */
    flashWREG->FDIAGCTRL = 0x00055001U;
    flashWREG->FEMUECC = ecc;
    /* Diagnostic trigger */
    flashWREG->FDIAGCTRL |= 0x01000000U;
    /*SAFETYMCUSW 139 S MR:13.7 <APPROVED> "Hardware status bit read check" */
    if((flashWREG->EESTATUS & 0x100U) != 0x100U)
    {
        /* No double bit error was detected */
        selftestFailNotification(CHECKFLASHEEPROMECC_FAIL3);
    }
    else
    {
        if((esmREG->SR4[0U] & 0x10U) != 0x10U)
        {
            /* EEPROM double bit error not captured in ESM */
            selftestFailNotification(CHECKFLASHEEPROMECC_FAIL4);
        }
        else
        {
            /* Clear uncorrectable error flag in flash wrapper */
            flashWREG->EESTATUS = 0x1100U;
            /* Read EEUNCERRADD register */
            regread = flashWREG->EEUNCERRADD;
            /* Clear ESM flag */
            esmREG->SR4[0U] = 0x10U;
        }
    }
}
checkPLL1Slip()
void checkPLL1Slip (void)
Check PLL1 Slip detection logic.
This function checks PLL1 Slip detection logic.
Definition at line 2276 of file sys_selftest.c.
References esmREG, selftestFailNotification(), and systemREG1.
{
    uint32 ghvsrc_bk, pllctl1_bk;
    /* Back up the the registers GHVSRC and PLLCTRL1 */
    ghvsrc_bk = systemREG1->GHVSRC;
    pllctl1_bk = systemREG1->PLLCTL1;
    /* Switch all clock domains to oscillator */
    systemREG1->GHVSRC = 0x00000000U;
    /* Disable Reset on PLL Slip and enable Bypass on PLL slip */
    systemREG1->PLLCTL1 &= 0x1FFFFFFFU;
    /* Force a PLL Slip */
    systemREG1->PLLCTL1 ^= 0x8000U;
    /* Wait till PLL slip flag is set */
    /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
    while((systemREG1->GBLSTAT & 0x300U) == 0U)
    {
    } /* Wait */
    if((esmREG->SR1[0U] & 0x400U) != 0x400U)
    {
        /* ESM flag not set */
        selftestFailNotification(CHECKPLL1SLIP_FAIL1);
    }
    else
    {
        /* Disable PLL1 */
        systemREG1->CSDISSET = 0x2U;
        /* Wait till PLL1 is disabled */
        /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
        while((systemREG1->CSDIS & 0x2U) == 0U)
        {
        } /* Wait */
        /* Restore the PLL multiplier value */
        systemREG1->PLLCTL1 ^= 0x8000U;
        /* Enable PLL1 */
        systemREG1->CSDISCLR = 0x2U;
        /* Wait till PLL1 is disabled */
        /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
        while((systemREG1->CSDIS & 0x2U) != 0U)
        {
        } /* Wait */
        /* Switch back to the initial clock source */
        systemREG1->GHVSRC = ghvsrc_bk;
        /* Clear PLL slip flag */
        systemREG1->GBLSTAT = 0x300U;
        /* Clear ESM flag */
        esmREG->SR1[0U] = 0x400U;
        /* Restore the PLLCTL1 register */
        systemREG1->PLLCTL1 = pllctl1_bk;
    }
}
checkPLL2Slip()
void checkPLL2Slip (void)
Check PLL2 Slip detection logic.
This function checks PLL2 Slip detection logic.
Definition at line 2349 of file sys_selftest.c.
References esmREG, systemREG1, and systemREG2.
{
    uint32 ghvsrc_bk;
    /* Back up the the register GHVSRC */
    ghvsrc_bk = systemREG1->GHVSRC;
    /* Switch all clock domains to oscillator */
    systemREG1->GHVSRC = 0x00000000U;
    
    /* Force a PLL2 Slip */
    systemREG2->PLLCTL3 ^= 0x8000U;
    /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
    while((esmREG->SR4[0U] & 0x400U) != 0x400U)
    {
        /* Wait till ESM flag is set */
    }
    /* Disable PLL2 */
    systemREG1->CSDISSET = 0x40U;
    /* Wait till PLL2 is disabled */
    /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
    while((systemREG1->CSDIS & 0x40U) == 0U)
    {
    } /* Wait */
    /* Restore the PLL 2 multiplier value */
    systemREG2->PLLCTL3 ^= 0x8000U;
    /* Enable PLL2 */
    systemREG1->CSDISCLR = 0x40U;
    /* Wait till PLL2 is disabled */
    /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
    while((systemREG1->CSDIS & 0x40U) != 0U)
    {
    } /* Wait */
    /* Switch back to the initial clock source */
    systemREG1->GHVSRC = ghvsrc_bk;
    /* Clear PLL slip flag */
    systemREG1->GBLSTAT = 0x300U;
    /* Clear ESM flag */
    esmREG->SR4[0U] = 0x400U;
}
checkRAMAddrParity()
void checkRAMAddrParity (void)
Check TCRAM Address parity error detection and signaling mechanism.
This function TCRAM Address parity error detection and signaling mechanism.
Definition at line 2408 of file sys_selftest.c.
{
    register uint64 ramread;
    volatile uint32 regread;
    uint32 tcram1ErrStat, tcram2ErrStat;
    
    /* Invert Address parity scheme */
    tcram1REG->RAMCTRL = 0x0D05000AU;
    tcram2REG->RAMCTRL = 0x0D05000AU;
    /* Read from both RAM banks */
    ramread = tcramA1bit;
    ramread = ramread | tcramB1bit; /* XOR-ing with ramread to avoid warnings */
    /* Switch back to Address parity scheme */
    tcram1REG->RAMCTRL = 0x0005000AU;
    tcram2REG->RAMCTRL = 0x0005000AU;
    /* Check for error status */
    tcram1ErrStat = tcram1REG->RAMERRSTATUS & 0x100U;
    tcram2ErrStat = tcram2REG->RAMERRSTATUS & 0x100U;
    /*SAFETYMCUSW 139 S MR:13.7 <APPROVED> "LDRA Tool issue" */
    /*SAFETYMCUSW 139 S MR:13.7 <APPROVED> "LDRA Tool issue" */
    if((tcram1ErrStat == 0U) || (tcram2ErrStat == 0U))
    {
        /* No Address parity error detected */
        selftestFailNotification(CHECKRAMADDRPARITY_FAIL1);
    }
    else
    {
        if((esmREG->SR1[1U] & 0x1400U) != 0x1400U)
        {
            /* Address parity error not reported to ESM */
            selftestFailNotification(CHECKRAMADDRPARITY_FAIL2);
        }
        else
        {
            /* Clear Address parity error flag */
            tcram1REG->RAMERRSTATUS = 0x300U;
            tcram2REG->RAMERRSTATUS = 0x300U;
            /* Clear ESM flag */
            esmREG->SR1[1U] = 0x1400U;
            /* The nERROR pin will become inactive once the LTC counter expires */
            esmREG->EKR = 0x5U;
            regread = tcram1REG->RAMPERADDR;
            regread = tcram2REG->RAMPERADDR;
        }
    }
}
checkRAMECC()
void checkRAMECC (void)
Check TCRAM ECC error detection logic.
This function checks TCRAM ECC error detection logic.
Definition at line 2017 of file sys_selftest.c.
{
    volatile uint64 ramread = 0U;
    volatile uint32 regread = 0U;
    uint32 tcram1ErrStat, tcram2ErrStat = 0U;
    
    uint64 tcramA1_bk = tcramA1bit;
    uint64 tcramB1_bk = tcramB1bit;
    uint64 tcramA2_bk = tcramA2bit;
    uint64 tcramB2_bk = tcramB2bit;
    /* Clear RAMOCUUR before setting RAMTHRESHOLD register */
    tcram1REG->RAMOCCUR = 0U;
    tcram2REG->RAMOCCUR = 0U;
    /* Set Single-bit Error Threshold Count as 1 */
    tcram1REG->RAMTHRESHOLD = 1U;
    tcram2REG->RAMTHRESHOLD = 1U;
    /* Enable single bit error generation */
    tcram1REG->RAMINTCTRL = 1U;
    tcram2REG->RAMINTCTRL = 1U;
    /* Enable writes to ECC RAM, enable ECC error response */
    tcram1REG->RAMCTRL = 0x0005010AU;
    tcram2REG->RAMCTRL = 0x0005010AU;
    /* Force a single bit error in both the banks */
    _coreDisableRamEcc_();
    tcramA1bitError ^= 1U;
    tcramB1bitError ^= 1U;
    _coreEnableRamEcc_();
    /* Read the corrupted data to generate single bit error */
    ramread = tcramA1bit;
    ramread = tcramB1bit;
    /* Check for error status */
    tcram1ErrStat = tcram1REG->RAMERRSTATUS & 0x1U;
    tcram2ErrStat = tcram2REG->RAMERRSTATUS & 0x1U;
    /*SAFETYMCUSW 139 S MR:13.7 <APPROVED> "LDRA Tool issue" */
    /*SAFETYMCUSW 139 S MR:13.7 <APPROVED> "LDRA Tool issue" */
    if((tcram1ErrStat == 0U) || (tcram2ErrStat == 0U))
    {
        /* TCRAM module does not reflect 1-bit error reported by CPU */
        selftestFailNotification(CHECKRAMECC_FAIL1);
    }
    else
    {
        if((esmREG->SR1[0U] & 0x14000000U) != 0x14000000U)
        {
            /* TCRAM 1-bit error not flagged in ESM */
            selftestFailNotification(CHECKRAMECC_FAIL2);
        }
        else
        {
            /* Clear single bit error flag in TCRAM module */
            tcram1REG->RAMERRSTATUS = 0x1U;
            tcram2REG->RAMERRSTATUS = 0x1U;
            /* Clear ESM status */
            esmREG->SR1[0U] = 0x14000000U;
        }
    }
    /* Force a double bit error in both the banks */
    _coreDisableRamEcc_();
    tcramA2bitError ^= 3U;
    tcramB2bitError ^= 3U;
    _coreEnableRamEcc_();
    /* Read the corrupted data to generate double bit error */
    ramread = tcramA2bit;
    ramread = tcramB2bit;
    regread = tcram1REG->RAMUERRADDR;
    regread = tcram2REG->RAMUERRADDR;
    /* disable writes to ECC RAM */
    tcram1REG->RAMCTRL = 0x0005000AU;
    tcram2REG->RAMCTRL = 0x0005000AU;
    /* Compute correct ECC */
    tcramA1bit = tcramA1_bk;
    tcramB1bit = tcramB1_bk;
    tcramA2bit = tcramA2_bk;
    tcramB2bit = tcramB2_bk;
}
checkRAMUERRTest()
void checkRAMUERRTest (void)
Run RAM test.
This function runs RAM test to test the redundant address decode and compare logic.
Definition at line 2469 of file sys_selftest.c.
{
    uint32 tcram1ErrStat, tcram2ErrStat = 0U;
    /* Trigger equality check */
    tcram1REG->RAMTEST = 0x018AU;
    tcram2REG->RAMTEST = 0x018AU;
    /* Wait till test is completed */
    while(tcram1REG->RAMTEST != 0x008AU)
    {
    } /* Wait */
    while(tcram2REG->RAMTEST != 0x008AU)
    {
    } /* Wait */
    /* Check for error status */
    tcram1ErrStat = tcram1REG->RAMERRSTATUS & 0x10U;
    tcram2ErrStat = tcram2REG->RAMERRSTATUS & 0x10U;
    if((tcram1ErrStat == 0x10U) || (tcram2ErrStat == 0x10U))
    {
        /* test failed */
        selftestFailNotification(CHECKRAMUERRTEST_FAIL1);
    }
    /* Trigger inequality check */
    tcram1REG->RAMTEST = 0x014AU;
    tcram2REG->RAMTEST = 0x014AU;
    /* Wait till test is completed */
    while(tcram1REG->RAMTEST != 0x004AU)
    {
    }/* Wait */
    while(tcram2REG->RAMTEST != 0x004AU)
    {
    }/* Wait */
    tcram1ErrStat = tcram1REG->RAMERRSTATUS & 0x10U;
    tcram2ErrStat = tcram2REG->RAMERRSTATUS & 0x10U;
    if((tcram1ErrStat == 0x10U) || (tcram2ErrStat == 0x10U))
    {
        /* test failed */
        selftestFailNotification(CHECKRAMUERRTEST_FAIL2);
    }
    else
    {
        tcram1REG->RAMERRSTATUS = 0x4U;
        tcram2REG->RAMERRSTATUS = 0x4U;
        /* Clear ESM flag */
        esmREG->SR1[1U] = 0x140U;
        esmREG->SSR2 = 0x140U;
        esmREG->EKR = 0x5U;
    }
    /* Disable RAM test mode */
    tcram1REG->RAMTEST = 0x5U;
    tcram2REG->RAMTEST = 0x5U;
}
cpuSelfTest()
void cpuSelfTest (uint32 no_of_intervals, uint32 max_timeout, boolean restart_test)
CPU self test Driver.
Parameters
in no_of_intervals - Number of Test Intervals to be
in max_timeout - Maximum Timeout to complete selected test Intervals
in restart_test - Restart the test from Interval 0 or Continue from where it stopped.
This function is called to perform CPU self test using STC module.
Definition at line 266 of file sys_selftest.c.
{
    volatile uint32 i = 0U;
/* USER CODE BEGIN (11) */
/* USER CODE END */
    /* Run specified no of test intervals starting from interval 0 */
    /* Start test from interval 0 or continue the test. */
    stcREG->STCGCR0 = no_of_intervals << 16U;
    if(restart_test)
    {
        stcREG->STCGCR0 |= 0x00000001U;
    }
    /* Configure Maximum time-out period */
    stcREG->STCTPR = max_timeout;
    /* wait for 16 VBUS clock cycles at least, based on HCLK to VCLK ratio */
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
    for (i=0U; i<(16U + (16U * 1U)); i++){ /* Wait */ }
    /* Enable self-test */
    stcREG->STCGCR1 = 0xAU;
/* USER CODE BEGIN (12) */
/* USER CODE END */
    /* Idle the CPU so that the self-test can start */
    _gotoCPUIdle_();
}
cpuSelfTestFail()
void cpuSelfTestFail (void)
CPU Self test check fail service routine.
This function is called if CPU Self test check fail.
Definition at line 1159 of file sys_selftest.c.
{
/* USER CODE BEGIN (46) */
/* USER CODE END */
    /* CPU self-test has failed.
     * CPU operation is not reliable.
     */
/* USER CODE BEGIN (47) */
/* USER CODE END */
    /*SAFETYMCUSW 5 C MR:NA <APPROVED> "for(;;) can be removed by adding "# if 0" and "# endif" in the user
       codes above and below" */
    /*SAFETYMCUSW 26 S MR:NA <APPROVED> "for(;;) can be removed by adding "# if 0" and "# endif" in the
       user codes above and below" */
    /*SAFETYMCUSW 28 D MR:NA <APPROVED> "for(;;) can be removed by adding "# if 0" and "# endif" in the
       user codes above and below" */
    for(;;)
    {
    }/* Wait */
/* USER CODE BEGIN (48) */
/* USER CODE END */
}
custom_dabort()
void custom_dabort (void)
Custom Data abort routine for the application.
Custom Data abort routine for the application.
Definition at line 1116 of file sys_selftest.c.
{
    /* Need custom data abort handler here.
     * This data abort is not caused due to diagnostic checks of flash and TCRAM ECC logic.
     */
/* USER CODE BEGIN (42) */
/* USER CODE END */
}
disableParity()
void disableParity (void)
Disable peripheral RAM parity.
This function disables RAM parity for all peripherals for which RAM parity check is enabled. This function is called after memoryInit in the startup
Definition at line 2972 of file sys_selftest.c.
{
    DMA_PARCR = 0x5U; /* Disable DMA RAM parity */
    VIM_PARCTL = 0x5U; /* Disable VIM RAM parity */
    canREG1->CTL = ((uint32)0x5U << 10U) | 1U; /* Disable CAN1 RAM parity */
    canREG2->CTL = ((uint32)0x5U << 10U) | 1U; /* Disable CAN2 RAM parity */
    canREG3->CTL = ((uint32)0x5U << 10U) | 1U; /* Disable CAN3 RAM parity */
    adcREG1->PARCR = 0x5U; /* Disable ADC1 RAM parity */
    adcREG2->PARCR = 0x5U; /* Disable ADC2 RAM parity */
    hetREG1->PCR = 0x5U; /* Disable HET1 RAM parity */
    htuREG1->PCR = 0x5U; /* Disable HTU1 RAM parity */
    hetREG2->PCR = 0x5U; /* Disable HET2 RAM parity */
    htuREG2->PCR = 0x5U; /* Disable HTU2 RAM parity */
}
dmaParityCheck()
void dmaParityCheck (void)
Routine to check DMA control packet RAM parity error detection and signaling mechanism.
Routine to check DMA control packet RAM parity error detection and signaling mechanism
Definition at line 1244 of file sys_selftest.c.
{
    volatile uint32 dmaread = 0U;
    uint32 dmaparcr_bk = DMA_PARCR;
/* USER CODE BEGIN (51) */
/* USER CODE END */
    /* Enable parity checking and parity test mode */
    DMA_PARCR = 0x0000010AU;
    /* Flip a bit in DMA RAM parity location */
    DMARAMPARLOC ^= 0x1U;
    /* Disable parity test mode */
    DMA_PARCR = 0x0000000AU;
    /* Cause parity error */
    dmaread = DMARAMLOC;
    /* Check if ESM group1 channel 3 is flagged */
    if ((esmREG->SR1[0U] & 0x8U) == 0U)
    {
        /* DMA RAM parity error was not flagged to ESM. */
        selftestFailNotification(DMAPARITYCHECK_FAIL1);
    }
    else
    {
        /* clear DMA parity error flag in DMA */
        DMA_PARADDR = 0x01000000U;
        /* clear ESM group1 channel 3 flag */
        esmREG->SR1[0U] = 0x8U;
        /* Enable parity checking and parity test mode */
        DMA_PARCR = 0x0000010AU;
        /* Revert back to correct data, flip bit 0 of the parity location */
        DMARAMPARLOC ^= 0x1U;
    }
    /* Restrore Parity Control register */
    DMA_PARCR = dmaparcr_bk;
/* USER CODE BEGIN (52) */
/* USER CODE END */
}
efcCheck()
uint32 efcCheck (void)
EFUSE module self check Driver.
Returns
Returns 0 if no error was detected during autoload and Stuck At Zero Test passed 1 if no error was detected during autoload but Stuck At Zero Test failed 2 if there was a single-bit error detected during autoload 3 if some other error occurred during autoload
This function self checks the EFUSE module.
Definition at line 582 of file sys_selftest.c.
Referenced by systemInit().
{
    uint32 efcStatus = 0U;
    uint32 status;
    
/* USER CODE BEGIN (27) */
/* USER CODE END */
    /* read the EFC Error Status Register */
    efcStatus = efcREG->ERROR;
/* USER CODE BEGIN (28) */
/* USER CODE END */
    if (efcStatus == 0x0U)
    {
        /* run stuck-at-zero test and check if it passed */
        if (efcStuckZeroTest()== TRUE)
        {
            /* start EFC ECC logic self-test */
            efcSelfTest();
            status = 0U;
        }
        else
        {
            /* EFC output is stuck-at-zero, device operation unreliable */
            selftestFailNotification(EFCCHECK_FAIL1);
            status = 1U;
        }
    }
    /* EFC Error Register is not zero */
    else
    {
        /* one-bit error detected during autoload */
        if (efcStatus == 0x15U)
        {
            /* start EFC ECC logic self-test */
            efcSelfTest();
            status = 2U;
        }
        else
        {
            /* Some other EFC error was detected */
            selftestFailNotification(EFCCHECK_FAIL1);
            status = 3U;
        }
    }
    return status;
}
efcGetConfigValue()
void efcGetConfigValue (efc_config_reg_t * config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
Parameters
in *config_reg pointer to the struct to which the initial or current value of the configuration registers need to be stored
in type whether initial or current value of the configuration registers need to be stored
InitialValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
CurrentValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
This function will copy the initial or current value (depending on the parameter 'type') of the configuration registers to the struct pointed by config_reg
Definition at line 2725 of file sys_selftest.c.
{
    if (type == InitialValue)
    {
        config_reg->CONFIG_BOUNDARY = EFC_BOUNDARY_CONFIGVALUE;
        config_reg->CONFIG_PINS = EFC_PINS_CONFIGVALUE;
        config_reg->CONFIG_SELFTESTCYCLES = EFC_SELFTESTCYCLES_CONFIGVALUE;
        config_reg->CONFIG_SELFTESTSIGN = EFC_SELFTESTSIGN_CONFIGVALUE;
    }
    else
    {
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "LDRA Tool issue" */
        config_reg->CONFIG_BOUNDARY = efcREG->BOUNDARY;
        config_reg->CONFIG_PINS = efcREG->PINS;
        config_reg->CONFIG_SELFTESTCYCLES = efcREG->SELF_TEST_CYCLES;
        config_reg->CONFIG_SELFTESTSIGN = efcREG->SELF_TEST_SIGN;
    }
}
efcSelfTest()
void efcSelfTest (void)
EFUSE module self check Driver.
This function self checks the EFSUE module.
Definition at line 697 of file sys_selftest.c.
{
/* USER CODE BEGIN (30) */
/* USER CODE END */
    /* configure self-test cycles */
    efcREG->SELF_TEST_CYCLES = 0x258U;
    /* configure self-test signature */
    efcREG->SELF_TEST_SIGN = 0x5362F97FU;
    /* configure boundary register to start ECC self-test */
    efcREG->BOUNDARY = 0x0000200FU;
}
efcStuckZeroTest()
boolean efcStuckZeroTest (void)
Checks to see if the EFUSE Stuck at zero test is completed successfully.
Returns
1 if EFUSE Stuck at zero test completed, otherwise 0.
Checks to see if the EFUSE Stuck at zero test is completed successfully.
Definition at line 641 of file sys_selftest.c.
References FALSE.
{
/* USER CODE BEGIN (29) */
/* USER CODE END */
    uint32 ESM_ESTATUS4, ESM_ESTATUS1;
    boolean result = FALSE;
    uint32 error_checks = EFC_INSTRUCTION_INFO_EN |
                                  EFC_INSTRUCTION_ERROR_EN |
                                  EFC_AUTOLOAD_ERROR_EN |
                                  EFC_SELF_TEST_ERROR_EN ;
    /* configure the output enable for auto load error , instruction info,
         instruction error, and self test error using boundary register
         and drive values one across all the errors */
    efcREG->BOUNDARY = ((uint32)OUTPUT_ENABLE | error_checks);
    /* Read from the pin register. This register holds the current values
         of above errors. This value should be 0x5c00.If not at least one of
         the above errors is stuck at 0. */
    if ((efcREG->PINS & 0x5C00U) == 0x5C00U)
    {
        ESM_ESTATUS4 = esmREG->SR4[0U];
        ESM_ESTATUS1 = esmREG->SR1[2U];
        /* check if the ESM group1 channel 41 is set and group3 channel 1 is set */
        if (((ESM_ESTATUS4 & 0x200U) == 0x200U) && ((ESM_ESTATUS1 & 0x2U) == 0x2U))
        {
           /* stuck-at-zero test passed */
           result = TRUE;
        }
    }
    /* put the pins back low */
    efcREG->BOUNDARY = OUTPUT_ENABLE;
    /* clear group1 flag */
    esmREG->SR4[0U] = 0x200U;
    /* clear group3 flag */
    esmREG->SR1[2U] = 0x2U;
    /* The nERROR pin will become inactive once the LTC counter expires */
    esmREG->EKR = 0x5U;
    return result;
}
enableParity()
void enableParity (void)
Enable peripheral RAM parity.
This function enables RAM parity for all peripherals for which RAM parity check is enabled. This function is called before memoryInit in the startup
Definition at line 2949 of file sys_selftest.c.
{
    DMA_PARCR = 0xAU; /* Enable DMA RAM parity */
    VIM_PARCTL = 0xAU; /* Enable VIM RAM parity */
    canREG1->CTL = ((uint32)0xAU << 10U) | 1U; /* Enable CAN1 RAM parity */
    canREG2->CTL = ((uint32)0xAU << 10U) | 1U; /* Enable CAN2 RAM parity */
    canREG3->CTL = ((uint32)0xAU << 10U) | 1U; /* Enable CAN3 RAM parity */
    adcREG1->PARCR = 0xAU; /* Enable ADC1 RAM parity */
    adcREG2->PARCR = 0xAU; /* Enable ADC2 RAM parity */
    hetREG1->PCR = 0xAU; /* Enable HET1 RAM parity */
    htuREG1->PCR = 0xAU; /* Enable HTU1 RAM parity */
    hetREG2->PCR = 0xAU; /* Enable HET2 RAM parity */
    htuREG2->PCR = 0xAU; /* Enable HTU2 RAM parity */
}
errata_PBIST_4()
void errata_PBIST_4 (void)
Workaround for the Errata PBIST#4.
This function is workaround for Errata PBIST#4. This function is designed to initialize the ROMs using the PBIST controller. The CPU will configure the PBIST controller to test the PBIST ROM and STC ROM. This function should be called at startup after system init before using the ROMs.
Note
: This Function uses register's which are not exposed to users through TRM , to run custom algorithm. User can use this function as Black box.
Definition at line 2785 of file sys_selftest.c.
References _pmuEnableCountersGlobal_(), _pmuGetCycleCount_(), _pmuResetCounters_(), _pmuStartCounters_(), _pmuStopCounters_(), and pmuCYCLE_COUNTER.
{
    volatile uint32 i = 0U;
    uint8 ROM_count;
    sint32 PBIST_wait_done_loop;
    uint32 pmuCalibration, pmuCount;
    /* PMU calibration */
    _pmuEnableCountersGlobal_();
    _pmuResetCounters_();
    _pmuStartCounters_(pmuCYCLE_COUNTER);
    _pmuStopCounters_(pmuCYCLE_COUNTER);
    pmuCalibration=_pmuGetCycleCount_();
    /* ROM_init Setup using special reserved registers as part of errata fix */
    /* (Only to be used in this function) */
    *(volatile uint32 *)0xFFFF0400U = 0x0000000AU;
    *(volatile uint32 *)0xFFFF040CU = 0x0000EE0AU;
    /* Loop for Executing PBIST ROM and STC ROM */
    for (ROM_count = 0U; ROM_count < 2U; ROM_count++)
    {
        PBIST_wait_done_loop = 0;
    
        /* Disable PBIST clocks and ROM clock */
        pbistREG->PACT = 0x0U;
        
        /* PBIST Clocks did not disable */
        if(pbistREG->PACT != 0x0U)
        {
            selftestFailNotification(PBISTSELFCHECK_FAIL3);
        }
        else
        {
            /* PBIST ROM clock frequency = HCLK frequency /2 */
            /* Disable memory self controller */
            systemREG1->MSTGCR = 0x00000105U;
            
            /* Disable Memory Initialization controller */
            systemREG1->MINITGCR = 0x5U;
            /* Enable memory self controller */
            systemREG1->MSTGCR = 0x0000010AU;
            /* Clear PBIST Done */
            systemREG1->MSTCGSTAT = 0x1U;
            
            /* Enable PBIST controller */
            systemREG1->MSINENA = 0x1U;
            /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
            /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
            /* wait for 32 VBUS clock cycles at least, based on HCLK to VCLK ratio */
            for (i=0U; i<(32U + (32U * 1U)); i++){ /* Wait */ }
            /* Enable PBIST clocks and ROM clock */
            pbistREG->PACT = 0x3U;
            /* CPU control of PBIST */
            pbistREG->DLR = 0x10U;
            /* Load PBIST ALGO to initialize the ROMs */
            *(volatile uint32 *)0xFFFFE400U = 0x00000001U;
            *(volatile uint32 *)0xFFFFE440U = 0x00000025U;
            *(volatile uint32 *)0xFFFFE404U = 0x62400001U;
            *(volatile uint32 *)0xFFFFE444U = 0x00000004U;
            *(volatile uint32 *)0xFFFFE408U = 0x00068003U;
            *(volatile uint32 *)0xFFFFE448U = 0x00000000U;
            *(volatile uint32 *)0xFFFFE40CU = 0x00000004U;
            *(volatile uint32 *)0xFFFFE44CU = 0x00006860U;
            *(volatile uint32 *)0xFFFFE410U = 0x00000000U;
            *(volatile uint32 *)0xFFFFE450U = 0x00000001U;
            *(volatile uint32 *)0xFFFFE540U = 0x000003E8U;
            *(volatile uint32 *)0xFFFFE550U = 0x00000001U;
            *(volatile uint32 *)0xFFFFE530U = 0x00000000U;
            
            /* SELECT ROM */
            if (ROM_count == 1U)
            {
                /* SELECT PBIST ROM */
                *(volatile uint32 *)0xFFFFE520U = 0x00000002U;
                *(volatile uint32 *)0xFFFFE524U = 0x00000000U;
                pbistREG->RAMT = 0x01002008U;
            }
            else
            {
                /* SELECT STC ROM */
                *(volatile uint32 *)0xFFFFE520U = 0xFFF0007CU;
                *(volatile uint32 *)0xFFFFE524U = 0x0A63FFFFU;
                pbistREG->RAMT = 0x02002008U;
            }
            /* Setup using special reserved registers as part of errata fix */
            /* (Only to be used in this function) */
            pbistREG->rsvd1[4U] = 1U;
            pbistREG->rsvd1[0U] = 3U;
            /* Start PMU counter */
            _pmuResetCounters_();
            _pmuStartCounters_(pmuCYCLE_COUNTER);
            /* PBIST_RUN */
            pbistREG->rsvd1[1U] = 1U;
            /* wait until memory self-test done is indicated */
            /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
            while ((systemREG1->MSTCGSTAT & 0x1U) != 0x1U)
            {
            }/* Wait */
            /* Stop PMU counter */
            _pmuStopCounters_(pmuCYCLE_COUNTER);
            
            /* Get CPU cycle count */
            pmuCount =_pmuGetCycleCount_();
            
            /* Calculate PBIST test complete time in ROM Clock */
            /* 2 - Divide value (Default is 2 in HALCoGen) */
            /* 1000 = 0x3E8 - Test Loop count in ROM Algorithm */
            pmuCount = pmuCount - pmuCalibration;
            PBIST_wait_done_loop = ((sint32)pmuCount/2) - 1000;
            /* Check PBIST status results (Address, Status, Count, etc...) */
            if ((pbistREG->FSRA0 | pbistREG->FSRA1 | pbistREG->FSRDL0 | pbistREG->rsvd3 |
                 pbistREG->FSRDL1 | pbistREG->rsvd4[0U] | pbistREG->rsvd4[1U]) != 0U)
            {
                /* PBIST Failure for the Algorithm chosen above */
                selftestFailNotification(PBISTSELFCHECK_FAIL1);
            }
            /* Check that the algorithm executed in the expected amount of time. */
            /* This time is dependent on the ROMCLKDIV selected */
            if ((PBIST_wait_done_loop <= 20) || (PBIST_wait_done_loop >= 200))
            {
                selftestFailNotification(PBISTSELFCHECK_FAIL2);
            }
            /* Disable PBIST clocks and ROM clock */
            pbistREG->PACT = 0x0U;
            /* Disable PBIST */
            systemREG1->MSTGCR &= 0xFFFFFFF0U;
            systemREG1->MSTGCR |= 0x5U;
        }
    } /* ROM Loop */
    /* ROM restore default setup */
    /* (must be completed before continuing) */
    *(volatile uint32 *)0xFFFF040CU = 0x0000AA0AU;
    *(volatile uint32 *)0xFFFF040CU = 0x0000AA05U;
    *(volatile uint32 *)0xFFFF0400U = 0x00000005U;
    _pmuDisableCountersGlobal_();
}
fmcBus2Check()
void fmcBus2Check (void)
Self Check Flash Bus2 Interface.
This function self checks Flash Bus2 Interface
Definition at line 760 of file sys_selftest.c.
References esmREG, flashWREG, and fmcECCcheck().
{
/* USER CODE BEGIN (32) */
/* USER CODE END */
    /* enable ECC logic inside FMC */
    flashWREG->FEDACCTRL1 = 0x000A060AU;
    if ((esmREG->SR1[0U] & 0x40U) == 0x40U)
    {
        /* a 1-bit error was detected during flash OTP read by flash module
           run a self-check on ECC logic inside FMC */
        /* clear ESM group1 channel 6 flag */
        esmREG->SR1[0U] = 0x40U;
        fmcECCcheck();
    }
    /* no 2-bit or 1-bit error detected during power-up */
    else
    {
        fmcECCcheck();
    }
/* USER CODE BEGIN (33) */
/* USER CODE END */
}
fmcECCcheck()
void fmcECCcheck (void)
Check Flash ECC Single Bit and multi Bit errors detection logic.
This function Checks Flash ECC Single Bit and multi Bit errors detection logic.
Definition at line 795 of file sys_selftest.c.
Referenced by fmcBus2Check().
{
    volatile uint32 otpread;
    volatile uint32 temp;
/* USER CODE BEGIN (34) */
/* USER CODE END */
    /* read location with deliberate 1-bit error */
    otpread = flash1bitError;
    if ((esmREG->SR1[0U] & 0x40U) == 0x40U)
    {
        /* 1-bit failure was indicated and corrected */
        flashWREG->FEDACSTATUS = 0x00010006U;
        /* clear ESM group1 channel 6 flag */
        esmREG->SR1[0U] = 0x40U;
        /* read location with deliberate 2-bit error */
        otpread = flash2bitError;
        if ((esmREG->SR1[2U] & 0x80U) == 0x80U)
        {
            /* 2-bit failure was detected correctly */
            temp = flashWREG->FUNCERRADD;
            flashWREG->FEDACSTATUS = 0x00020100U;
            /* clear ESM group3 channel 7 */
            esmREG->SR1[2U] = 0x80U;
            /* The nERROR pin will become inactive once the LTC counter expires */
            esmREG->EKR = 0x5U;
        }
        else
        {
            /* ECC logic inside FMC cannot detect 2-bit error */
            selftestFailNotification(FMCECCCHECK_FAIL1);
        }
    }
    else
    {
        /* ECC logic inside FMC cannot detect 1-bit error */
        selftestFailNotification(FMCECCCHECK_FAIL1);
    }
/* USER CODE BEGIN (35) */
/* USER CODE END */
}
het1ParityCheck()
void het1ParityCheck (void)
Routine to check HET1 RAM parity error detection and signaling mechanism.
Routine to check HET1 RAM parity error detection and signaling mechanism
Definition at line 1301 of file sys_selftest.c.
References hetREG1.
{
    volatile uint32 nhetread = 0U;
    uint32 hetpcr_bk = hetREG1->PCR;
/* USER CODE BEGIN (53) */
/* USER CODE END */
    /* Set TEST mode and enable parity checking */
    hetREG1->PCR = 0x0000010AU;
    /* flip parity bit */
    NHET1RAMPARLOC ^= 0x1U;
    /* Disable TEST mode */
    hetREG1->PCR = 0x0000000AU;
    /* read to cause parity error */
    nhetread = NHET1RAMLOC;
    /* check if ESM group1 channel 7 is flagged */
    if ((esmREG->SR1[0U] & 0x80U) ==0U)
    {
        /* NHET1 RAM parity error was not flagged to ESM. */
        selftestFailNotification(HET1PARITYCHECK_FAIL1);
    }
    else
    {
        /* clear ESM group1 channel 7 flag */
        esmREG->SR1[0U] = 0x80U;
        /* Set TEST mode and enable parity checking */
        hetREG1->PCR = 0x0000010AU;
        /* Revert back to correct data, flip bit 0 of the parity location */
        NHET1RAMPARLOC ^= 0x1U;
    }
    /* Restore Parity comtrol register */
    hetREG1->PCR = hetpcr_bk;
/* USER CODE BEGIN (54) */
/* USER CODE END */
}
het2ParityCheck()
void het2ParityCheck (void)
Routine to check HET2 RAM parity error detection and signaling mechanism.
Routine to check HET2 RAM parity error detection and signaling mechanism
Definition at line 1411 of file sys_selftest.c.
References hetREG2.
{
    volatile uint32 nhetread = 0U;
    uint32 hetpcr_bk = hetREG2->PCR;
    uint32 esmCh7Stat, esmCh34Stat = 0U;
    
/* USER CODE BEGIN (57) */
/* USER CODE END */
    /* Set TEST mode and enable parity checking */
    hetREG2->PCR = 0x0000010AU;
    /* flip parity bit */
    NHET2RAMPARLOC ^= 0x1U;
    /* Disable TEST mode */
    hetREG2->PCR = 0x0000000AU;
    /* read to cause parity error */
    nhetread = NHET2RAMLOC;
    /* check if ESM group1 channel 7 or 34 (If not reserved) is flagged */
    esmCh7Stat = esmREG->SR1[0U] & 0x80U;
    esmCh34Stat = esmREG->SR4[0U] & 0x4U;
    if ((esmCh7Stat == 0U) && (esmCh34Stat ==0U))
    {
        /* NHET2 RAM parity error was not flagged to ESM. */
        selftestFailNotification(HET2PARITYCHECK_FAIL1);
    }
    else
    {
        /* clear ESM group1 channel 7 flag */
        esmREG->SR1[0U] = 0x80U;
        /* clear ESM group1 channel 34 flag */
        esmREG->SR4[0U] = 0x4U;
        /* Set TEST mode and enable parity checking */
        hetREG2->PCR = 0x0000010AU;
        /* Revert back to correct data, flip bit 0 of the parity location */
        NHET2RAMPARLOC ^= 0x1U;
    }
    /* Restore parity control register */
    hetREG2->PCR = hetpcr_bk;
/* USER CODE BEGIN (58) */
/* USER CODE END */
}
htu1ParityCheck()
void htu1ParityCheck (void)
Routine to check HTU1 RAM parity error detection and signaling mechanism.
Routine to check HTU1 RAM parity error detection and signaling mechanism
Definition at line 1355 of file sys_selftest.c.
{
    volatile uint32 hturead = 0U;
    uint32 htupcr_bk = htuREG1->PCR;
/* USER CODE BEGIN (55) */
/* USER CODE END */
    /* Enable parity and TEST mode */
    htuREG1->PCR = 0x0000010AU;
    /* flip parity bit */
    HTU1PARLOC ^= 0x1U;
    /* Disable parity RAM test mode */
    htuREG1->PCR = 0x0000000AU;
    /* read to cause parity error */
    hturead = HTU1RAMLOC;
    /* check if ESM group1 channel 8 is flagged */
    if ((esmREG->SR1[0U] & 0x100U) == 0U)
    {
        /* HTU1 RAM parity error was not flagged to ESM. */
        selftestFailNotification(HTU1PARITYCHECK_FAIL1);
    }
    else
    {
        /* Clear HTU parity error flag */
        htuREG1->PAR = 0x00010000U;
        esmREG->SR1[0U] = 0x100U;
        /* Enable parity and TEST mode */
        htuREG1->PCR = 0x0000010AU;
        /* Revert back to correct data, flip bit 0 of the parity location */
        HTU1PARLOC ^= 0x1U;
    }
    /* Restore Parity control register */
    htuREG1->PCR = htupcr_bk;
/* USER CODE BEGIN (56) */
/* USER CODE END */
}
htu2ParityCheck()
void htu2ParityCheck (void)
Routine to check HTU2 RAM parity error detection and signaling mechanism.
Routine to check HTU2 RAM parity error detection and signaling mechanism
Definition at line 1471 of file sys_selftest.c.
{
    volatile uint32 hturead = 0U;
    uint32 htupcr_bk = htuREG2->PCR;
/* USER CODE BEGIN (59) */
/* USER CODE END */
    /* Enable parity and TEST mode */
    htuREG2->PCR = 0x0000010AU;
    /* flip parity bit */
    HTU2PARLOC ^= 0x1U;
    /* Disable parity RAM test mode */
    htuREG2->PCR = 0x0000000AU;
    /* read to cause parity error */
    hturead = HTU2RAMLOC;
    /* check if ESM group1 channel 8 is flagged */
    if ((esmREG->SR1[0U] & 0x100U) == 0U)
    {
        /* HTU2 RAM parity error was not flagged to ESM. */
        selftestFailNotification(HTU2PARITYCHECK_FAIL1);
    }
    else
    {
        /* Clear HTU parity error flag */
        htuREG2->PAR = 0x00010000U;
        esmREG->SR1[0U] = 0x100U;
        /* Enable parity and TEST mode */
        htuREG2->PCR = 0x0000010AU;
        /* Revert back to correct data, flip bit 0 of the parity location */
        HTU2PARLOC ^= 0x1U;
    }
    /* Restore parity control register*/
    htuREG2->PCR = htupcr_bk;
/* USER CODE BEGIN (60) */
/* USER CODE END */
}
memoryInit()
void memoryInit (uint32 ram)
Memory Initialization Driver.
This function is called to perform Memory initialization of selected RAM's.
Definition at line 184 of file sys_selftest.c.
References systemREG1.
{
/* USER CODE BEGIN (6) */
/* USER CODE END */
    /* Enable Memory Hardware Initialization */
    systemREG1->MINITGCR = 0xAU;
    /* Enable Memory Hardware Initialization for selected RAM's */
    systemREG1->MSINENA = ram;
    /* Wait until Memory Hardware Initialization complete */
    /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
    while((systemREG1->MSTCGSTAT & 0x00000100U) != 0x00000100U)
    {
    }/* Wait */
    /* Disable Memory Hardware Initialization */
    systemREG1->MINITGCR = 0x5U;
/* USER CODE BEGIN (7) */
/* USER CODE END */
}
memoryPort0TestFailNotification()
void memoryPort0TestFailNotification (uint32 groupSelect, uint32 dataSelect, uint32 address, uint32 data)
Memory Port 0 test fail notification.
Parameters
in groupSelect Failing Ram group select:
in dataSelect Failing Ram data select:
in address Failing Ram offset:
in data Failing data at address:
Note
This function has to be provide by the user.
Definition at line 83 of file notification.c.
{
/* enter user code between the USER CODE BEGIN and USER CODE END. */
/* USER CODE BEGIN (5) */
/* USER CODE END */
}
memoryPort1TestFailNotification()
void memoryPort1TestFailNotification (uint32 groupSelect, uint32 dataSelect, uint32 address, uint32 data)
Memory Port 1 test fail notification.
Parameters
in groupSelect Failing Ram group select:
in dataSelect Failing Ram data select:
in address Failing Ram offset:
in data Failing data at address:
Note
This function has to be provide by the user.
Definition at line 93 of file notification.c.
{
/* enter user code between the USER CODE BEGIN and USER CODE END. */
/* USER CODE BEGIN (7) */
/* USER CODE END */
}
mibspi1ParityCheck()
void mibspi1ParityCheck (void)
Routine to check MIBSPI1 RAM parity error detection and signaling mechanism.
Routine to check MIBSPI1 RAM parity error detection and signaling mechanism
Definition at line 1825 of file sys_selftest.c.
References mibspiPARRAM1, and mibspiREG1.
{
    volatile uint32 spiread = 0U;
    uint32 mibspie_bk = mibspiREG1->MIBSPIE;
    uint32 mibspictl_bk = mibspiREG1->UERRCTRL;
/* USER CODE BEGIN (71) */
/* USER CODE END */
    /* enable multi-buffered mode */
    mibspiREG1->MIBSPIE = 0x1U;
    /* enable parity error detection */
    mibspiREG1->UERRCTRL = (mibspiREG1->UERRCTRL & 0xFFFFFFF0U) | (0xAU);
    /* enable parity test mode */
    mibspiREG1->UERRCTRL |= 0x00000100U;
    /* flip bit 0 of the parity location */
    mibspiPARRAM1 ^= 0x1U;
    /* disable parity test mode */
    mibspiREG1->UERRCTRL &= 0xFFFFFEFFU;
    /* read from MibSPI1 RAM to cause parity error */
    spiread = MIBSPI1RAMLOC;
    /* check if ESM group1 channel 17 is flagged */
    if ((esmREG->SR1[0U] & 0x20000U) == 0U)
    {
        /* No MibSPI1 RAM parity error was flagged to ESM. */
        selftestFailNotification(MIBSPI1PARITYCHECK_FAIL1);
    }
    else
    {
        /* clear parity error flags */
        mibspiREG1->UERRSTAT = 0x3U;
        /* clear ESM group1 channel 17 flag */
        esmREG->SR1[0U] = 0x20000U;
        /* enable parity test mode */
        mibspiREG1->UERRCTRL |= 0x00000100U;
        /* Revert back to correct data, flip bit 0 of the parity location */
        mibspiPARRAM1 ^= 0x1U;
    }
    /* Restore MIBSPI control registers */
    mibspiREG1->UERRCTRL = mibspictl_bk;
    mibspiREG1->MIBSPIE = mibspie_bk;
/* USER CODE BEGIN (72) */
/* USER CODE END */
}
mibspi3ParityCheck()
void mibspi3ParityCheck (void)
Routine to check MIBSPI3 RAM parity error detection and signaling mechanism.
Routine to check MIBSPI3 RAM parity error detection and signaling mechanism
Definition at line 1889 of file sys_selftest.c.
References mibspiPARRAM3, and mibspiREG3.
{
    volatile uint32 spiread = 0U;
    uint32 mibspie_bk = mibspiREG3->MIBSPIE;
    uint32 mibspictl_bk = mibspiREG3->UERRCTRL;
/* USER CODE BEGIN (73) */
/* USER CODE END */
    /* enable multi-buffered mode */
    mibspiREG3->MIBSPIE = 0x1U;
    /* enable parity test mode */
    mibspiREG3->UERRCTRL |= 0x00000100U;
    /* flip bit 0 of the parity location */
    mibspiPARRAM3 ^= 0x1U;
    /* enable parity error detection */
    mibspiREG3->UERRCTRL = (mibspiREG3->UERRCTRL & 0xFFFFFFF0U) | (0xAU);
    /* disable parity test mode */
    mibspiREG3->UERRCTRL &= 0xFFFFFEFFU;
    /* read from MibSPI3 RAM to cause parity error */
    spiread = MIBSPI3RAMLOC;
    /* check if ESM group1 channel 18 is flagged */
    if ((esmREG->SR1[0U] & 0x40000U) == 0U)
    {
        /* No MibSPI3 RAM parity error was flagged to ESM. */
        selftestFailNotification(MIBSPI3PARITYCHECK_FAIL1);
    }
    else
    {
        /* clear parity error flags */
        mibspiREG3->UERRSTAT = 0x3U;
        /* clear ESM group1 channel 18 flag */
        esmREG->SR1[0U] = 0x40000U;
        /* enable parity test mode */
        mibspiREG3->UERRCTRL |= 0x00000100U;
        /* Revert back to correct data, flip bit 0 of the parity location */
        mibspiPARRAM3 ^= 0x1U;
    }
    /* Restore MIBSPI control registers */
    mibspiREG3->UERRCTRL = mibspictl_bk;
    mibspiREG3->MIBSPIE = mibspie_bk;
/* USER CODE BEGIN (74) */
/* USER CODE END */
}
mibspi5ParityCheck()
void mibspi5ParityCheck (void)
Routine to check MIBSPI5 RAM parity error detection and signaling mechanism.
Routine to check MIBSPI5 RAM parity error detection and signaling mechanism
Definition at line 1953 of file sys_selftest.c.
References mibspiPARRAM5, and mibspiREG5.
{
    volatile uint32 spiread = 0U;
    uint32 mibspie_bk = mibspiREG5->MIBSPIE;
    uint32 mibspictl_bk = mibspiREG5->UERRCTRL;
/* USER CODE BEGIN (75) */
/* USER CODE END */
    /* enable multi-buffered mode */
    mibspiREG5->MIBSPIE = 0x1U;
    /* enable parity test mode */
    mibspiREG5->UERRCTRL |= 0x00000100U;
    /* flip bit 0 of the parity location */
    mibspiPARRAM5 ^= 0x1U;
    /* enable parity error detection */
    mibspiREG5->UERRCTRL = (mibspiREG5->UERRCTRL & 0xFFFFFFF0U) | (0xAU);
    /* disable parity test mode */
    mibspiREG5->UERRCTRL &= 0xFFFFFEFFU;
    /* read from MibSPI5 RAM to cause parity error */
    spiread = MIBSPI5RAMLOC;
    /* check if ESM group1 channel 24 is flagged */
    if ((esmREG->SR1[0U] & 0x01000000U) == 0U)
    {
        /* No MibSPI5 RAM parity error was flagged to ESM. */
        selftestFailNotification(MIBSPI5PARITYCHECK_FAIL1);
    }
    else
    {
        /* clear parity error flags */
        mibspiREG5->UERRSTAT = 0x3U;
        /* clear ESM group1 channel 24 flag */
        esmREG->SR1[0U] = 0x01000000U;
        /* enable parity test mode */
        mibspiREG5->UERRCTRL |= 0x00000100U;
        /* Revert back to correct data, flip bit 0 of the parity location */
        mibspiPARRAM5 ^= 0x1U;
    }
    /* Restore MIBSPI control registers */
    mibspiREG5->UERRCTRL = mibspictl_bk;
    mibspiREG5->MIBSPIE = mibspie_bk;
/* USER CODE BEGIN (76) */
/* USER CODE END */
}
pbistGetConfigValue()
void pbistGetConfigValue (pbist_config_reg_t * config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
Parameters
in *config_reg pointer to the struct to which the initial or current value of the configuration registers need to be stored
in type whether initial or current value of the configuration registers need to be stored
InitialValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
CurrentValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
This function will copy the initial or current value (depending on the parameter 'type') of the configuration registers to the struct pointed by config_reg
Definition at line 2646 of file sys_selftest.c.
{
    if (type == InitialValue)
    {
        config_reg->CONFIG_RAMT = PBIST_RAMT_CONFIGVALUE;
        config_reg->CONFIG_DLR = PBIST_DLR_CONFIGVALUE;
        config_reg->CONFIG_PACT = PBIST_PACT_CONFIGVALUE;
        config_reg->CONFIG_PBISTID = PBIST_PBISTID_CONFIGVALUE;
        config_reg->CONFIG_OVER = PBIST_OVER_CONFIGVALUE;
        config_reg->CONFIG_FSRDL1 = PBIST_FSRDL1_CONFIGVALUE;
        config_reg->CONFIG_ROM = PBIST_ROM_CONFIGVALUE;
        config_reg->CONFIG_ALGO = PBIST_ALGO_CONFIGVALUE;
        config_reg->CONFIG_RINFOL = PBIST_RINFOL_CONFIGVALUE;
        config_reg->CONFIG_RINFOU = PBIST_RINFOU_CONFIGVALUE;
    }
    else
    {
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "LDRA Tool issue" */
        config_reg->CONFIG_RAMT = pbistREG->RAMT;
        config_reg->CONFIG_DLR = pbistREG->DLR;
        config_reg->CONFIG_PACT = pbistREG->PACT;
        config_reg->CONFIG_PBISTID = pbistREG->PBISTID;
        config_reg->CONFIG_OVER = pbistREG->OVER;
        config_reg->CONFIG_FSRDL1 = pbistREG->FSRDL1;
        config_reg->CONFIG_ROM = pbistREG->ROM;
        config_reg->CONFIG_ALGO = pbistREG->ALGO;
        config_reg->CONFIG_RINFOL = pbistREG->RINFOL;
        config_reg->CONFIG_RINFOU = pbistREG->RINFOU;
    }
}
pbistIsTestCompleted()
boolean pbistIsTestCompleted (void)
Checks to see if the PBIST test is completed.
Returns
1 if PBIST test completed, otherwise 0.
Checks to see if the PBIST test is completed.
Definition at line 503 of file sys_selftest.c.
References systemREG1.
{
/* USER CODE BEGIN (22) */
/* USER CODE END */
    return ((systemREG1->MSTCGSTAT & 0x1U) != 0U);
/* USER CODE BEGIN (23) */
/* USER CODE END */
}
pbistIsTestPassed()
boolean pbistIsTestPassed (void)
Checks to see if the PBIST test is completed successfully.
Returns
1 if PBIST test passed, otherwise 0.
Checks to see if the PBIST test is completed successfully.
Definition at line 522 of file sys_selftest.c.
{
/* USER CODE BEGIN (24) */
/* USER CODE END */
    boolean status;
    if (pbistREG->FSRF0 == 0U)
    {
        status = TRUE;
    }
    else
    {
        status = FALSE;
    }
/* USER CODE BEGIN (25) */
/* USER CODE END */
    return status;
}
pbistPortTestStatus()
boolean pbistPortTestStatus (uint32 port)
Checks to see if the PBIST Port test is completed successfully.
Parameters
in port - Select the port to get the status.
Returns
1 if PBIST Port test completed successfully, otherwise 0.
Checks to see if the selected PBIST Port test is completed successfully.
Definition at line 551 of file sys_selftest.c.
References PBIST_PORT0.
{
    boolean status;
/* USER CODE BEGIN (26) */
/* USER CODE END */
    if(port == (uint32)PBIST_PORT0)
    {
      status = (pbistREG->FSRF0 == 0U);
    }
    else
    {
      /* Invalid Input */
      status = FALSE;
    }
    return status;
}
pbistRun()
void pbistRun (uint32 raminfoL, uint32 algomask)
CPU self test Driver.
Parameters
in raminfoL - Select the list of RAM to be tested.
in algomask - Select the list of Algorithm to be run.
This function performs Memory Built-in Self test using PBIST module.
Definition at line 421 of file sys_selftest.c.
References systemREG1.
{
    volatile uint32 i = 0U;
/* USER CODE BEGIN (17) */
/* USER CODE END */
    /* PBIST ROM clock frequency = HCLK frequency /2 */
    /* Disable memory self controller */
    systemREG1->MSTGCR = 0x00000105U;
    /* Disable Memory Initialization controller */
    systemREG1->MINITGCR = 0x5U;
    /* Enable PBIST controller */
    systemREG1->MSINENA = 0x1U;
    /* Enable memory self controller */
    systemREG1->MSTGCR = 0x0000010AU;
    /* wait for 32 VBUS clock cycles at least, based on HCLK to VCLK ratio */
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
    for (i=0U; i<(32U + (32U * 1U)); i++){ /* Wait */ }
/* USER CODE BEGIN (18) */
/* USER CODE END */
    /* Enable PBIST clocks and ROM clock */
    pbistREG->PACT = 0x3U;
    /* Select all algorithms to be tested */
    pbistREG->ALGO = algomask;
    /* Select RAM groups */
    pbistREG->RINFOL = raminfoL;
    /* Select all RAM groups */
    pbistREG->RINFOU = 0x00000000U;
    /* ROM contents will not override RINFOx settings */
    pbistREG->OVER = 0x0U;
    /* Algorithm code is loaded from ROM */
    pbistREG->ROM = 0x3U;
    /* Start PBIST */
    pbistREG->DLR = 0x14U;
/* USER CODE BEGIN (19) */
/* USER CODE END */
}
pbistSelfCheck()
void pbistSelfCheck (void)
PBIST self test Driver.
This function is called to perform PBIST self test.
Note
This Function uses register's which are not exposed to users through TRM , to run custom algorithm to make PBIST Fail. Users can use this function as Black box.
Definition at line 312 of file sys_selftest.c.
{
    volatile uint32 i = 0U;
    uint32 PBIST_wait_done_loop = 0U;
/* USER CODE BEGIN (13) */
/* USER CODE END */
    /* Run a diagnostic check on the memory self-test controller */
    /* First set up the PBIST ROM clock as this clock frequency is limited to 90MHz */
    /* Disable PBIST clocks and ROM clock */
    pbistREG->PACT = 0x0U;
    
    /* PBIST ROM clock frequency = HCLK frequency /2 */
    /* Disable memory self controller */
    systemREG1->MSTGCR = 0x00000105U;
    
    /* Disable Memory Initialization controller */
    systemREG1->MINITGCR = 0x5U;
    /* Enable memory self controller */
    systemREG1->MSTGCR = 0x0000010AU;
    /* Clear PBIST Done */
    systemREG1->MSTCGSTAT = 0x1U;
    
    /* Enable PBIST controller */
    systemREG1->MSINENA = 0x1U;
    /* wait for 32 VBUS clock cycles at least, based on HCLK to VCLK ratio */
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
    for (i=0U; i<(32U + (32U * 1U)); i++){ /* Wait */ }
/* USER CODE BEGIN (14) */
/* USER CODE END */
    /* Enable PBIST clocks and ROM clock */
    pbistREG->PACT = 0x3U;
    /* CPU control of PBIST */
    pbistREG->DLR = 0x10U;
    /* Custom always fail algo, this will not use the ROM and just set a fail */
    pbistREG->RAMT = 0x00002000U;
    *(volatile uint32 *)0xFFFFE400U = 0x4C000001U;
    *(volatile uint32 *)0xFFFFE440U = 0x00000075U;
    *(volatile uint32 *)0xFFFFE404U = 0x4C000002U;
    *(volatile uint32 *)0xFFFFE444U = 0x00000075U;
    *(volatile uint32 *)0xFFFFE408U = 0x4C000003U;
    *(volatile uint32 *)0xFFFFE448U = 0x00000075U;
    *(volatile uint32 *)0xFFFFE40CU = 0x4C000004U;
    *(volatile uint32 *)0xFFFFE44CU = 0x00000075U;
    *(volatile uint32 *)0xFFFFE410U = 0x4C000005U;
    *(volatile uint32 *)0xFFFFE450U = 0x00000075U;
    *(volatile uint32 *)0xFFFFE414U = 0x4C000006U;
    *(volatile uint32 *)0xFFFFE454U = 0x00000075U;
    *(volatile uint32 *)0xFFFFE418U = 0x00000000U;
    *(volatile uint32 *)0xFFFFE458U = 0x00000001U;
    /* PBIST_RUN */
    pbistREG->rsvd1[1U] = 1U;
    /* wait until memory self-test done is indicated */
    /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
    while ((systemREG1->MSTCGSTAT & 0x1U) != 0x1U)
    {
        PBIST_wait_done_loop++;
    }/* Wait */
    /* Check for the failure */
    if ((pbistREG->FSRF0 & 0x1U) != 0x1U)
    {
        /* No failure was indicated even if the always fail algorithm was run*/
        selftestFailNotification(PBISTSELFCHECK_FAIL1);
/* USER CODE BEGIN (15) */
/* USER CODE END */
    }
    else
    {
        /* Check that the algorithm executed in the expected amount of time. */
        /* This time is dependent on the ROMCLKDIV selected above */
        if (PBIST_wait_done_loop >= 2U)
        {
            selftestFailNotification(PBISTSELFCHECK_FAIL2);
        }
        
        /* Disable PBIST clocks and ROM clock */
        pbistREG->PACT = 0x0U;
        /* Disable PBIST */
        systemREG1->MSTGCR &= 0xFFFFFFF0U;
        systemREG1->MSTGCR |= 0x5U;
/* USER CODE BEGIN (16) */
/* USER CODE END */
    }
}
pbistStop()
void pbistStop (void)
Routine to stop PBIST test enabled.
This function is called to stop PBIST after test is performed.
Definition at line 482 of file sys_selftest.c.
{
/* USER CODE BEGIN (20) */
/* USER CODE END */
    /* disable pbist clocks and ROM clock */
    pbistREG->PACT = 0x0U;
    systemREG1->MSTGCR &= 0xFFFFFFF0U;
    systemREG1->MSTGCR |= 0x5U;
/* USER CODE BEGIN (21) */
/* USER CODE END */
}
selftestFailNotification()
void selftestFailNotification (uint32 flag)
Self test fail service routine.
This function is called if there is a self test fail with appropriate flag
Definition at line 58 of file sys_selftest.c.
Referenced by adc1ParityCheck(), adc2ParityCheck(), can1ParityCheck(), can2ParityCheck(), can3ParityCheck(), checkClockMonitor(), checkFlashEEPROMECC(), checkPLL1Slip(), and systemInit().
{
/* USER CODE BEGIN (1) */
/* USER CODE END */
}
stcGetConfigValue()
void stcGetConfigValue (stc_config_reg_t * config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
Parameters
in *config_reg pointer to the struct to which the initial or current value of the configuration registers need to be stored
in type whether initial or current value of the configuration registers need to be stored
InitialValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
CurrentValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
This function will copy the initial or current value (depending on the parameter 'type') of the configuration registers to the struct pointed by config_reg
Definition at line 2691 of file sys_selftest.c.
{
    if (type == InitialValue)
    {
        config_reg->CONFIG_STCGCR0 = STC_STCGCR0_CONFIGVALUE;
        config_reg->CONFIG_STCGCR1 = STC_STCGCR1_CONFIGVALUE;
        config_reg->CONFIG_STCTPR = STC_STCTPR_CONFIGVALUE;
        config_reg->CONFIG_STCSCSCR = STC_STCSCSCR_CONFIGVALUE;
    }
    else
    {
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "LDRA Tool issue" */
        config_reg->CONFIG_STCGCR0 = stcREG->STCGCR0;
        config_reg->CONFIG_STCGCR1 = stcREG->STCGCR1;
        config_reg->CONFIG_STCTPR = stcREG->STCTPR;
        config_reg->CONFIG_STCSCSCR = stcREG->STCSCSCR;
    }
}
stcSelfCheck()
void stcSelfCheck (void)
STC module self check Driver.
This function is called to perform STC module self check.
Definition at line 216 of file sys_selftest.c.
References systemREG2.
{
/* USER CODE BEGIN (8) */
/* USER CODE END */
    volatile uint32 i = 0U;
    /* Run a diagnostic check on the CPU self-test controller */
    /* First set up the STC clock divider as STC is only supported up to 90MHz */
    /* STC clock is now normal mode CPU clock frequency/2 = 180MHz/2 */
    systemREG2->STCCLKDIV = 0x01000000U;
    /* Select one test interval, restart self-test next time, 0x00010001 */
    stcREG->STCGCR0 = 0x00010001U;
    /* Enable comparator self-check and stuck-at-0 fault insertion in CPU, 0x1A */
    stcREG->STCSCSCR = 0x1AU;
    /* Maximum time-out period */
    stcREG->STCTPR = 0xFFFFFFFFU;
    /* wait for 16 VBUS clock cycles at least, based on HCLK to VCLK ratio */
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "Wait for few clock cycles (Value of i not used)" */
    for (i=0U; i<(16U + (16U * 1U)); i++){ /* Wait */ }
    /* Enable self-test */
    stcREG->STCGCR1 = 0xAU;
/* USER CODE BEGIN (9) */
/* USER CODE END */
    /* Idle the CPU so that the self-test can start */
    _gotoCPUIdle_();
/* USER CODE BEGIN (10) */
/* USER CODE END */
}
stcSelfCheckFail()
void stcSelfCheckFail (void)
STC Self test check fail service routine.
This function is called if STC Self test check fail.
Definition at line 1130 of file sys_selftest.c.
{
/* USER CODE BEGIN (43) */
/* USER CODE END */
    /* CPU self-test controller's own self-test failed.
     * It is not possible to verify that STC is capable of indicating a CPU self-test error.
     * It is not recommended to continue operation.
     */
    /* User can add small piece of code to take system to Safe state using user code section.
     * Note: Just removing the for(;;) will take the system to unknown state under ST failure,
     * since it is not handled by HALCoGen driver */
/* USER CODE BEGIN (44) */
/* USER CODE END */
    /*SAFETYMCUSW 5 C MR:NA <APPROVED> "for(;;) can be removed by adding "# if 0" and "# endif" in the user
       codes above and below" */
    /*SAFETYMCUSW 26 S MR:NA <APPROVED> "for(;;) can be removed by adding "# if 0" and "# endif" in the
       user codes above and below" */
    /*SAFETYMCUSW 28 D MR:NA <APPROVED> "for(;;) can be removed by adding "# if 0" and "# endif" in the
       user codes above and below" */
    for(;;)
    {
    }/* Wait */
/* USER CODE BEGIN (45) */
/* USER CODE END */
}
vimParityCheck()
void vimParityCheck (void)
Routine to check VIM RAM parity error detection and signaling mechanism.
Routine to check VIM RAM parity error detection and signaling mechanism
Definition at line 1187 of file sys_selftest.c.
{
    volatile uint32 vimramread = 0U;
    uint32 vimparctl_bk = VIM_PARCTL;
/* USER CODE BEGIN (49) */
/* USER CODE END */
    /* Enable parity checking and parity test mode */
    VIM_PARCTL = 0x0000010AU;
    /* flip a bit in the VIM RAM parity location */
    VIMRAMPARLOC ^= 0x1U;
    /* disable parity test mode */
    VIM_PARCTL = 0x0000000AU;
    /* cause parity error */
    vimramread = VIMRAMLOC;
    /* check if ESM group1 channel 15 is flagged */
    if ((esmREG->SR1[0U] & 0x8000U) ==0U)
    {
        /* VIM RAM parity error was not flagged to ESM. */
        selftestFailNotification(VIMPARITYCHECK_FAIL1);
    }
    else
    {
        /* clear VIM RAM parity error flag in VIM */
        VIM_PARFLG = 0x1U;
        /* clear ESM group1 channel 15 flag */
        esmREG->SR1[0U] = 0x8000U;
        /* Enable parity checking and parity test mode */
        VIM_PARCTL = 0x0000010AU;
        /* Revert back to correct data, flip bit 0 of the parity location */
        VIMRAMPARLOC ^= 0x1U;
    }
    /* Restore Parity Control register */
    VIM_PARCTL = vimparctl_bk;
/* USER CODE BEGIN (50) */
/* USER CODE END */
}