generated_launchpad/include/system.h File Reference
System Driver Header File.
#include `reg_system.h`
#include `reg_flash.h`
#include `reg_tcram.h`
Classes
struct system_config_reg
struct tcmflash_config_reg
struct sram_config_reg
Macros
#define SYS_DOZE_MODE 0x000F3F02U
#define SYS_SNOOZE_MODE 0x000F3F03U
#define SYS_SLEEP_MODE 0x000FFFFFU
#define LPO_TRIM_VALUE (((*(volatile uint32 *)0xF00801B4U) & 0xFFFF0000U)>>16U)
#define SYS_EXCEPTION (*(volatile uint32 *)0xFFFFFFE4U)
#define POWERON_RESET 0x8000U
#define OSC_FAILURE_RESET 0x4000U
#define WATCHDOG_RESET 0x2000U
#define ICEPICK_RESET 0x2000U
#define CPU_RESET 0x0020U
#define SW_RESET 0x0010U
#define WATCHDOG_STATUS (*(volatile uint32 *)0xFFFFFC98U)
#define DEVICE_ID_REV (*(volatile uint32 *)0xFFFFFFF0U)
#define OSC_FREQ 16.0F
Oscillator clock source exported from HALCoGen GUI.
#define PLL1_FREQ 160.00F
PLL 1 clock source exported from HALCoGen GUI.
#define LPO_LF_FREQ 0.080F
LPO Low Freq Oscillator source exported from HALCoGen GUI.
#define LPO_HF_FREQ 10.000F
LPO High Freq Oscillator source exported from HALCoGen GUI.
#define PLL2_FREQ 160.00F
#define GCLK_FREQ 160.000F
GCLK domain frequency exported from HALCoGen GUI.
#define HCLK_FREQ 160.000F
HCLK domain frequency exported from HALCoGen GUI.
#define RTI_FREQ 80.000F
RTI Clock frequency exported from HALCoGen GUI.
#define AVCLK1_FREQ 80.000F
AVCLK1 Domain frequency exported from HALCoGen GUI.
#define AVCLK2_FREQ 80.000F
AVCLK2 Domain frequency exported from HALCoGen GUI.
#define AVCLK3_FREQ 0.000F
AVCLK3 Domain frequency exported from HALCoGen GUI.
#define AVCLK4_FREQ 80.000F
AVCLK4 Domain frequency exported from HALCoGen GUI.
#define VCLK1_FREQ 80.000F
VCLK1 Domain frequency exported from HALCoGen GUI.
#define VCLK2_FREQ 80.000F
VCLK2 Domain frequency exported from HALCoGen GUI.
#define VCLK3_FREQ 80.000F
VCLK3 Domain frequency exported from HALCoGen GUI.
#define VCLK4_FREQ 80.000F
VCLK4 Domain frequency exported from HALCoGen GUI.
#define SYS_PRE1 (SYS_PLL1)
Alias name for RTI1CLK PRE clock source.
#define SYS_PRE2 (SYS_PLL1)
Alias name for RTI2CLK pre clock source.
#define SYS_SYSPC1_CONFIGVALUE 0U
#define SYS_SYSPC2_CONFIGVALUE 1U
#define SYS_SYSPC7_CONFIGVALUE 0U
#define SYS_SYSPC8_CONFIGVALUE 0U
#define SYS_SYSPC9_CONFIGVALUE 1U
#define SYS_CSDIS_CONFIGVALUE
#define SYS_CDDIS_CONFIGVALUE
#define SYS_GHVSRC_CONFIGVALUE
#define SYS_VCLKASRC_CONFIGVALUE
#define SYS_RCLKSRC_CONFIGVALUE
#define SYS_MSTGCR_CONFIGVALUE 0x00000105U
#define SYS_MINITGCR_CONFIGVALUE 0x5U
#define SYS_MSINENA_CONFIGVALUE 0U
#define SYS_PLLCTL1_CONFIGVALUE_1
#define SYS_PLLCTL1_CONFIGVALUE_2 (((SYS_PLLCTL1_CONFIGVALUE_1) & 0xE0FFFFFFU) | (uint32)((uint32)(1U - 1U) << 24U))
#define SYS_PLLCTL2_CONFIGVALUE
#define SYS_UERFLAG_CONFIGVALUE 0U
#define SYS_LPOMONCTL_CONFIGVALUE_1 ((uint32)((uint32)1U << 24U) | LPO_TRIM_VALUE)
#define SYS_LPOMONCTL_CONFIGVALUE_2 ((uint32)((uint32)1U << 24U) | (uint32)((uint32)16U << 8U) | 16U)
#define SYS_CLKTEST_CONFIGVALUE 0x000A0000U
#define SYS_DFTCTRLREG1_CONFIGVALUE 0x00002205U
#define SYS_DFTCTRLREG2_CONFIGVALUE 0x5U
#define SYS_GPREG1_CONFIGVALUE 0x0005FFFFU
#define SYS_RAMGCR_CONFIGVALUE 0x00050000U
#define SYS_BMMCR1_CONFIGVALUE 0xAU
#define SYS_MMUGCR_CONFIGVALUE 0U
#define SYS_CLKCNTL_CONFIGVALUE
#define SYS_ECPCNTL_CONFIGVALUE
#define SYS_DEVCR1_CONFIGVALUE 0xAU
#define SYS_SYSECR_CONFIGVALUE 0x00004000U
#define SYS2_PLLCTL3_CONFIGVALUE_1
#define SYS2_PLLCTL3_CONFIGVALUE_2 (((SYS2_PLLCTL3_CONFIGVALUE_1) & 0xE0FFFFFFU) | (uint32)((uint32)(1U - 1U) << 24U))
#define SYS2_STCCLKDIV_CONFIGVALUE 0U
#define SYS2_CLK2CNTL_CONFIGVALUE (1U | 0x00000100U)
#define SYS2_VCLKACON1_CONFIGVALUE
#define SYS2_CLKSLIP_CONFIGVALUE 0x5U
#define SYS2_EFC_CTLEN_CONFIGVALUE 0x5U
#define FSM_WR_ENA_HL (*(volatile uint32 *)0xFFF87288U)
#define EEPROM_CONFIG_HL (*(volatile uint32 *)0xFFF872B8U)
#define TCMFLASH_FRDCNTL_CONFIGVALUE (0x00000000U | (uint32)((uint32)3U << 8U) | (uint32)((uint32)1U << 4U) | 1U)
#define TCMFLASH_FEDACCTRL1_CONFIGVALUE 0x000A0005U
#define TCMFLASH_FEDACCTRL2_CONFIGVALUE 0U
#define TCMFLASH_FEDACSDIS_CONFIGVALUE 0U
#define TCMFLASH_FBPROT_CONFIGVALUE 0U
#define TCMFLASH_FBSE_CONFIGVALUE 0U
#define TCMFLASH_FBAC_CONFIGVALUE 0xFU
#define TCMFLASH_FBFALLBACK_CONFIGVALUE
#define TCMFLASH_FPAC1_CONFIGVALUE 0x00C80001U
#define TCMFLASH_FPAC2_CONFIGVALUE 0U
#define TCMFLASH_FMAC_CONFIGVALUE 0U
#define TCMFLASH_FLOCK_CONFIGVALUE 0x55AAU
#define TCMFLASH_FDIAGCTRL_CONFIGVALUE 0x000A0000U
#define TCMFLASH_FEDACSDIS2_CONFIGVALUE 0U
#define SRAM_RAMCTRL_CONFIGVALUE 0x0005000AU
#define SRAM_RAMTHRESHOLD_CONFIGVALUE 1U
#define SRAM_RAMINTCTRL_CONFIGVALUE 1U
#define SRAM_RAMTEST_CONFIGVALUE 0x5U
#define SRAM_RAMADDRDECVECT_CONFIGVALUE 0U
Typedefs
typedef struct system_config_reg system_config_reg_t
typedef struct tcmflash_config_reg tcmflash_config_reg_t
typedef struct sram_config_reg sram_config_reg_t
Enumerations
enum systemClockSource {
SYS_OSC = 0U,
SYS_PLL1 = 1U,
SYS_EXTERNAL1 = 3U,
SYS_LPO_LOW = 4U,
SYS_LPO_HIGH = 5U,
SYS_PLL2 = 6U,
SYS_EXTERNAL2 = 7U,
SYS_VCLK = 9U
 }
Alias names for clock sources.
enum flashWPowerModes { SYS_SLEEP = 0U,
SYS_STANDBY = 1U,
SYS_ACTIVE = 3U
 }
Alias names for flash bank power modes.
Functions
void systemGetConfigValue (system_config_reg_t *config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
void tcmflashGetConfigValue (tcmflash_config_reg_t *config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
void setupPLL (void)
void trimLPO (void)
void setupFlash (void)
void periphInit (void)
void mapClocks (void)
void systemInit (void)
Initializes System Driver.
void systemPowerDown (uint32 mode)
void sramGetConfigValue (sram_config_reg_t *config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
Detailed Description
System Driver Header File.
Date
07-July-2017
Version
04.07.00
This file contains:
Definitions
Types
which are relevant for the System driver.
Macro Definition Documentation
AVCLK1_FREQ
#define AVCLK1_FREQ 80.000F
AVCLK1 Domain frequency exported from HALCoGen GUI.
AVCLK Domain frequency exported from HALCoGen GUI
Definition at line 167 of file system.h.
AVCLK2_FREQ
#define AVCLK2_FREQ 80.000F
AVCLK2 Domain frequency exported from HALCoGen GUI.
AVCLK2 Domain frequency exported from HALCoGen GUI
Definition at line 174 of file system.h.
AVCLK3_FREQ
#define AVCLK3_FREQ 0.000F
AVCLK3 Domain frequency exported from HALCoGen GUI.
AVCLK3 Domain frequency exported from HALCoGen GUI
Definition at line 181 of file system.h.
AVCLK4_FREQ
#define AVCLK4_FREQ 80.000F
AVCLK4 Domain frequency exported from HALCoGen GUI.
AVCLK4 Domain frequency exported from HALCoGen GUI
Definition at line 188 of file system.h.
GCLK_FREQ
#define GCLK_FREQ 160.000F
GCLK domain frequency exported from HALCoGen GUI.
GCLK domain frequency exported from HALCoGen GUI
Definition at line 146 of file system.h.
HCLK_FREQ
#define HCLK_FREQ 160.000F
HCLK domain frequency exported from HALCoGen GUI.
HCLK domain frequency exported from HALCoGen GUI
Definition at line 153 of file system.h.
LPO_HF_FREQ
#define LPO_HF_FREQ 10.000F
LPO High Freq Oscillator source exported from HALCoGen GUI.
LPO High Freq Oscillator source exported from HALCoGen GUI
Definition at line 132 of file system.h.
LPO_LF_FREQ
#define LPO_LF_FREQ 0.080F
LPO Low Freq Oscillator source exported from HALCoGen GUI.
LPO Low Freq Oscillator source exported from HALCoGen GUI
Definition at line 125 of file system.h.
OSC_FREQ
#define OSC_FREQ 16.0F
Oscillator clock source exported from HALCoGen GUI.
Oscillator clock source exported from HALCoGen GUI
Definition at line 111 of file system.h.
PLL1_FREQ
#define PLL1_FREQ 160.00F
PLL 1 clock source exported from HALCoGen GUI.
PLL 2 clock source exported from HALCoGen GUI.
PLL 1 clock source exported from HALCoGen GUI
PLL 2 clock source exported from HALCoGen GUI
RTI_FREQ
#define RTI_FREQ 80.000F
RTI Clock frequency exported from HALCoGen GUI.
RTI Clock frequency exported from HALCoGen GUI
Definition at line 160 of file system.h.
SYS2_PLLCTL3_CONFIGVALUE_1
#define SYS2_PLLCTL3_CONFIGVALUE_1
Value:
((uint32)((uint32)(2U - 1U) << 29U)\
                                    | (uint32)((uint32)0x1FU << 24U) \
                                    | (uint32)((uint32)(6U - 1U)<< 16U) \
                                    | (uint32)(0x7700U))
Definition at line 380 of file system.h.
SYS2_VCLKACON1_CONFIGVALUE
#define SYS2_VCLKACON1_CONFIGVALUE
Value:
((uint32)((uint32)1U << 24U) \
                                    | (uint32)((uint32)1U << 20U) \
                                    | (uint32)((uint32)SYS_VCLK << 16U)\
                                    | (uint32)((uint32)1U << 8U)\
                                    | (uint32)((uint32)1U << 4U) \
                                    | (uint32)((uint32)SYS_VCLK << 0U))
Definition at line 388 of file system.h.
SYS_CDDIS_CONFIGVALUE
#define SYS_CDDIS_CONFIGVALUE
Value:
((uint32)((uint32)0U << 4U)\
                                | (uint32)((uint32)0U << 5U)\
                                | (uint32)((uint32)0U << 8U)\
                                | (uint32)((uint32)0U << 9U)\
                                | (uint32)((uint32)1U << 10U)\
                                | (uint32)((uint32)0U << 11U))
Definition at line 310 of file system.h.
SYS_CLKCNTL_CONFIGVALUE
#define SYS_CLKCNTL_CONFIGVALUE
Value:
(0x00000100U \
                                    | (uint32)((uint32)1U << 16U) \
                                    | (uint32)((uint32)1U << 24U))
Definition at line 369 of file system.h.
SYS_CSDIS_CONFIGVALUE
#define SYS_CSDIS_CONFIGVALUE
Value:
(0x00000000U\
                                | 0x00000000U \
                                | 0x00000008U \
                                | 0x00000080U \
                                | 0x00000000U \
                                | 0x00000000U \
                                | 0x00000000U\
                                | 0x4U)
Definition at line 301 of file system.h.
SYS_ECPCNTL_CONFIGVALUE
#define SYS_ECPCNTL_CONFIGVALUE
Value:
((uint32)((uint32)0U << 24U)\
                                    | (uint32)((uint32)0U << 23U)\
                                    | (uint32)((uint32)(8U - 1U) & 0xFFFFU))
Definition at line 373 of file system.h.
SYS_GHVSRC_CONFIGVALUE
#define SYS_GHVSRC_CONFIGVALUE
Value:
((uint32)((uint32)SYS_OSC << 24U) \
                                | (uint32)((uint32)SYS_OSC << 16U) \
                                | (uint32)((uint32)SYS_PLL1 << 0U))
Definition at line 317 of file system.h.
SYS_PLLCTL1_CONFIGVALUE_1
#define SYS_PLLCTL1_CONFIGVALUE_1
Value:
((uint32)0x00000000U \
                                    | (uint32)0x20000000U \
                                    | (uint32)((uint32)0x1FU << 24U) \
                                    | (uint32)0x00000000U \
                                    | (uint32)((uint32)(6U - 1U)<< 16U)\
                                    | (uint32)(0x7700U))
Definition at line 335 of file system.h.
SYS_PLLCTL2_CONFIGVALUE
#define SYS_PLLCTL2_CONFIGVALUE
Value:
((uint32)0x00000000U\
                                    | (uint32)((uint32)255U << 22U)\
                                    | (uint32)((uint32)7U << 12U)\
                                    | (uint32)((uint32)(2U - 1U)<< 9U)\
                                    | (uint32)61U)
Definition at line 344 of file system.h.
SYS_PRE1
#define SYS_PRE1 (SYS_PLL1)
Alias name for RTI1CLK PRE clock source.
This is an alias name for the RTI1CLK pre clock source. This can be either:
Oscillator
Pll
32 kHz Oscillator
External
Low Power Oscillator Low
Low Power Oscillator High
Flexray Pll
Definition at line 233 of file system.h.
SYS_PRE2
#define SYS_PRE2 (SYS_PLL1)
Alias name for RTI2CLK pre clock source.
This is an alias name for the RTI2CLK pre clock source. This can be either:
Oscillator
Pll
32 kHz Oscillator
External
Low Power Oscillator Low
Low Power Oscillator High
Flexray Pll
Definition at line 249 of file system.h.
SYS_RCLKSRC_CONFIGVALUE
#define SYS_RCLKSRC_CONFIGVALUE
Value:
((uint32)((uint32)1U << 24U)\
                                    | (uint32)((uint32)SYS_VCLK << 16U)\
                                    | (uint32)((uint32)1U << 8U)\
                                    | (uint32)((uint32)SYS_VCLK << 0U))
Definition at line 324 of file system.h.
SYS_VCLKASRC_CONFIGVALUE
#define SYS_VCLKASRC_CONFIGVALUE
Value:
((uint32)((uint32)SYS_VCLK << 8U)\
                                    | (uint32)((uint32)SYS_VCLK << 0U))
Definition at line 321 of file system.h.
TCMFLASH_FBFALLBACK_CONFIGVALUE
#define TCMFLASH_FBFALLBACK_CONFIGVALUE
Value:
((uint32)((uint32)SYS_ACTIVE << 14U) \
                                            | (uint32)((uint32)3U << 12U) \
                                            | (uint32)((uint32)3U << 10U) \
                                            | (uint32)((uint32)3U << 8U) \
                                            | (uint32)((uint32)3U << 6U) \
                                            | (uint32)((uint32)3U << 4U) \
                                            | (uint32)((uint32)SYS_ACTIVE << 2U) \
                                            | (uint32)((uint32)SYS_ACTIVE << 0U))
Definition at line 454 of file system.h.
VCLK1_FREQ
#define VCLK1_FREQ 80.000F
VCLK1 Domain frequency exported from HALCoGen GUI.
VCLK1 Domain frequency exported from HALCoGen GUI
Definition at line 195 of file system.h.
VCLK2_FREQ
#define VCLK2_FREQ 80.000F
VCLK2 Domain frequency exported from HALCoGen GUI.
VCLK2 Domain frequency exported from HALCoGen GUI
Definition at line 202 of file system.h.
VCLK3_FREQ
#define VCLK3_FREQ 80.000F
VCLK3 Domain frequency exported from HALCoGen GUI.
VCLK3 Domain frequency exported from HALCoGen GUI
Definition at line 209 of file system.h.
VCLK4_FREQ
#define VCLK4_FREQ 80.000F
VCLK4 Domain frequency exported from HALCoGen GUI.
VCLK4 Domain frequency exported from HALCoGen GUI
Definition at line 216 of file system.h.
Enumeration Type Documentation
flashWPowerModes
enum flashWPowerModes
Alias names for flash bank power modes.
This enumeration is used to provide alias names for the flash bank power modes:
sleep
standby
active
Enumerator
SYS_SLEEP Alias for flash bank power mode sleep
SYS_STANDBY Alias for flash bank power mode standby
SYS_ACTIVE Alias for flash bank power mode active
Definition at line 413 of file system.h.
{
    SYS_SLEEP = 0U,
    SYS_STANDBY = 1U,
    SYS_ACTIVE = 3U
};
systemClockSource
enum systemClockSource
Alias names for clock sources.
This enumeration is used to provide alias names for the clock sources:
Oscillator
Pll1
External1
Low Power Oscillator Low
Low Power Oscillator High
PLL2
External2
Synchronous VCLK1
Enumerator
SYS_OSC Alias for oscillator clock Source
SYS_PLL1 Alias for Pll1 clock Source
SYS_EXTERNAL1 Alias for external clock Source
SYS_LPO_LOW Alias for low power oscillator low clock Source
SYS_LPO_HIGH Alias for low power oscillator high clock Source
SYS_PLL2 Alias for Pll2 clock Source
SYS_EXTERNAL2 Alias for external 2 clock Source
SYS_VCLK Alias for synchronous VCLK1 clock Source
Definition at line 78 of file system.h.
{
    SYS_OSC = 0U,
    SYS_PLL1 = 1U,
    SYS_EXTERNAL1 = 3U,
    SYS_LPO_LOW = 4U,
    SYS_LPO_HIGH = 5U,
    SYS_PLL2 = 6U,
    SYS_EXTERNAL2 = 7U,
    SYS_VCLK = 9U
};
Function Documentation
mapClocks()
void mapClocks (void)
Initialize Clock Tree:
Disable / Enable clock domain
Wait for until clocks are locked
Map device clock domains to desired sources and configure top-level dividers
All clock domains are working off the default clock sources until now
The below assignments can be easily modified using the HALCoGen GUI
Setup GCLK, HCLK and VCLK clock source for normal operation, power down mode and after wakeup
Setup RTICLK1 and RTICLK2 clocks
Setup asynchronous peripheral clock sources for AVCLK1 and AVCLK2
Setup synchronous peripheral clock dividers for VCLK1, VCLK2, VCLK3
Definition at line 241 of file system.c.
References systemREG1.
{
    uint32 SYS_CSVSTAT, SYS_CSDIS;
/* USER CODE BEGIN (11) */
/* USER CODE END */
    systemREG1->CDDIS = (uint32)((uint32)0U << 4U) /* AVCLK1 , 1 - OFF, 0 - ON */
                      | (uint32)((uint32)0U << 5U) /* AVCLK2 , 1 - OFF, 0 - ON */
                      | (uint32)((uint32)0U << 8U) /* VCLK3 , 1 - OFF, 0 - ON */
                      | (uint32)((uint32)0U << 9U) /* VCLK4 , 1 - OFF, 0 - ON */
                      | (uint32)((uint32)1U << 10U) /* AVCLK3 , 1 - OFF, 0 - ON */
                      | (uint32)((uint32)0U << 11U); /* AVCLK4 , 1 - OFF, 0 - ON */
    /* Work Around for Errata SYS#46:
     *
     * Errata Description:
     * Clock Source Switching Not Qualified with Clock Source Enable And Clock Source Valid
     * Workaround:
     * Always check the CSDIS register to make sure the clock source is turned on and check
     * the CSVSTAT register to make sure the clock source is valid. Then write to GHVSRC to switch the
       clock.
     */
    SYS_CSVSTAT = systemREG1->CSVSTAT;
    SYS_CSDIS = systemREG1->CSDIS;
    while ((SYS_CSVSTAT & ((SYS_CSDIS ^ 0xFFU) & 0xFFU)) != ((SYS_CSDIS ^ 0xFFU) & 0xFFU))
    {
        SYS_CSVSTAT = systemREG1->CSVSTAT;
        SYS_CSDIS = systemREG1->CSDIS;
    } /* Wait */
/* USER CODE BEGIN (12) */
/* USER CODE END */
    systemREG1->GHVSRC = (uint32)((uint32)SYS_OSC << 24U)
                       | (uint32)((uint32)SYS_OSC << 16U)
                       | (uint32)((uint32)SYS_PLL1 << 0U);
    systemREG1->RCLKSRC = (uint32)((uint32)1U << 24U)
                        | (uint32)((uint32)SYS_VCLK << 16U)
                        | (uint32)((uint32)1U << 8U)
                        | (uint32)((uint32)SYS_VCLK << 0U);
    systemREG1->VCLKASRC = (uint32)((uint32)SYS_VCLK << 8U)
                         | (uint32)((uint32)SYS_VCLK << 0U);
    systemREG1->CLKCNTL = (systemREG1->CLKCNTL & 0xF0FFFFFFU)
                         | (uint32)((uint32)1U << 24U);
    systemREG1->CLKCNTL = (systemREG1->CLKCNTL & 0xFFF0FFFFU)
                         | (uint32)((uint32)1U << 16U);
    systemREG2->CLK2CNTL = (systemREG2->CLK2CNTL & 0xFFFFF0F0U)
                         | (uint32)((uint32)1U << 8U)
                         | (uint32)((uint32)1U << 0U);
    systemREG2->VCLKACON1 = (uint32)((uint32)(1U - 1U) << 24U)
                           | (uint32)((uint32)0U << 20U)
                           | (uint32)((uint32)SYS_VCLK << 16U)
                           | (uint32)((uint32)(1U - 1U) << 8U)
                           | (uint32)((uint32)0U << 4U)
                           | (uint32)((uint32)SYS_VCLK << 0U);
/* USER CODE BEGIN (13) */
/* USER CODE END */
    /* Now the PLLs are locked and the PLL outputs can be sped up */
    /* The R-divider was programmed to be 0xF. Now this divider is changed to programmed value */
    systemREG1->PLLCTL1 = (systemREG1->PLLCTL1 & 0xE0FFFFFFU) | (uint32)((uint32)(1U -
      1U) << 24U);
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "LDRA Tool issue" */
    systemREG2->PLLCTL3 = (systemREG2->PLLCTL3 & 0xE0FFFFFFU) | (uint32)((uint32)(1U -
      1U) << 24U);
    /* Enable/Disable Frequency modulation */
    systemREG1->PLLCTL2 |= 0x00000000U;
/* USER CODE BEGIN (14) */
/* USER CODE END */
}
periphInit()
void periphInit (void)
Disable Peripherals before peripheral powerup
Release peripherals from reset and enable clocks to all peripherals
Power-up all peripherals
Enable Peripherals
Definition at line 214 of file system.c.
References pcrREG, and systemREG1.
Referenced by systemInit().
{
/* USER CODE BEGIN (9) */
/* USER CODE END */
    systemREG1->CLKCNTL &= 0xFFFFFEFFU;
    pcrREG->PSPWRDWNCLR0 = 0xFFFFFFFFU;
    pcrREG->PSPWRDWNCLR1 = 0xFFFFFFFFU;
    pcrREG->PSPWRDWNCLR2 = 0xFFFFFFFFU;
    pcrREG->PSPWRDWNCLR3 = 0xFFFFFFFFU;
    systemREG1->CLKCNTL |= 0x00000100U;
/* USER CODE BEGIN (10) */
/* USER CODE END */
}
setupFlash()
void setupFlash (void)
Setup flash read mode, address wait states and data wait states
Setup flash access wait states for bank 7
Disable write access to flash state machine registers
Setup flash bank power modes
Definition at line 177 of file system.c.
References flashWREG.
{
/* USER CODE BEGIN (6) */
/* USER CODE END */
    flashWREG->FRDCNTL = 0x00000000U
                       | (uint32)((uint32)3U << 8U)
                       | (uint32)((uint32)1U << 4U)
                       | 1U;
    FSM_WR_ENA_HL = 0x5U;
    EEPROM_CONFIG_HL = 0x00000002U
                     | (uint32)((uint32)3U << 16U) ;
/* USER CODE BEGIN (7) */
/* USER CODE END */
    FSM_WR_ENA_HL = 0xAU;
    flashWREG->FBFALLBACK = 0x00000000U
                          | (uint32)((uint32)SYS_ACTIVE << 14U) /* BANK 7 */
                          | (uint32)((uint32)SYS_ACTIVE << 2U) /* BANK 1 */
                          | (uint32)((uint32)SYS_ACTIVE << 0U); /* BANK 0 */
/* USER CODE BEGIN (8) */
/* USER CODE END */
}
setupPLL()
void setupPLL (void)
Configure PLL control registers
 Initialize Pll1:
Setup pll control register 1:
Setup reset on oscillator slip
Setup bypass on pll slip
setup Pll output clock divider to max before Lock
Setup reset on oscillator fail
Setup reference clock divider
Setup Pll multiplier
Setup pll control register 2
Setup spreading rate
Setup bandwidth adjustment
Setup internal Pll output divider
Setup spreading amount
Initialize Pll2:
Setup pll2 control register :
setup Pll output clock divider to max before Lock
Setup reference clock divider
Setup internal Pll output divider
Setup Pll multiplier
Enable PLL(s) to start up or Lock
Definition at line 74 of file system.c.
References systemREG1.
Referenced by systemInit().
{
/* USER CODE BEGIN (3) */
/* USER CODE END */
    /* Disable PLL1 and PLL2 */
    systemREG1->CSDISSET = 0x00000002U | 0x00000040U;
    /*SAFETYMCUSW 28 D MR:NA <APPROVED> "Hardware status bit read check" */
    while((systemREG1->CSDIS & 0x42U) != 0x42U)
    {
    /* Wait */
    }
    /* Clear Global Status Register */
    systemREG1->GBLSTAT = 0x301U;
    systemREG1->PLLCTL1 = (uint32)0x00000000U
                        | (uint32)0x20000000U
                        | (uint32)((uint32)0x1FU << 24U)
                        | (uint32)0x00000000U
                        | (uint32)((uint32)(6U - 1U)<< 16U)
                        | (uint32)(0x7700U);
    systemREG1->PLLCTL2 = (uint32)((uint32)255U << 22U)
                        | (uint32)((uint32)7U << 12U)
                        | (uint32)((uint32)(2U - 1U) << 9U)
                        | (uint32)61U;
    systemREG2->PLLCTL3 = (uint32)((uint32)(2U - 1U) << 29U)
                        | (uint32)((uint32)0x1FU << 24U)
                        | (uint32)((uint32)(6U - 1U)<< 16U)
                        | (uint32)(0x7700U);
    systemREG1->CSDIS = 0x00000000U
                      | 0x00000000U
                      | 0x00000008U
                      | 0x00000080U
                      | 0x00000000U
                      | 0x00000000U
                      | 0x00000000U;
}
sramGetConfigValue()
void sramGetConfigValue (sram_config_reg_t * config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
Parameters
in *config_reg pointer to the struct to which the initial or current value of the configuration registers need to be stored
in type whether initial or current value of the configuration registers need to be stored
InitialValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
CurrentValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
This function will copy the initial or current value (depending on the parameter 'type') of the configuration registers to the struct pointed by config_reg
Definition at line 647 of file system.c.
{
    if (type == InitialValue)
    {
        config_reg->CONFIG_RAMCTRL[0U] = SRAM_RAMCTRL_CONFIGVALUE;
        config_reg->CONFIG_RAMTHRESHOLD[0U] = SRAM_RAMTHRESHOLD_CONFIGVALUE;
        config_reg->CONFIG_RAMINTCTRL[0U] = SRAM_RAMINTCTRL_CONFIGVALUE;
        config_reg->CONFIG_RAMTEST[0U] = SRAM_RAMTEST_CONFIGVALUE;
        config_reg->CONFIG_RAMADDRDECVECT[0U] = SRAM_RAMADDRDECVECT_CONFIGVALUE;
        config_reg->CONFIG_RAMCTRL[1U] = SRAM_RAMCTRL_CONFIGVALUE;
        config_reg->CONFIG_RAMTHRESHOLD[1U] = SRAM_RAMTHRESHOLD_CONFIGVALUE;
        config_reg->CONFIG_RAMINTCTRL[1U] = SRAM_RAMINTCTRL_CONFIGVALUE;
        config_reg->CONFIG_RAMTEST[1U] = SRAM_RAMTEST_CONFIGVALUE;
        config_reg->CONFIG_RAMADDRDECVECT[1U] = SRAM_RAMADDRDECVECT_CONFIGVALUE;
    }
    else
    {
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "LDRA Tool issue" */
        config_reg->CONFIG_RAMCTRL[0U] = tcram1REG->RAMCTRL;
        config_reg->CONFIG_RAMTHRESHOLD[0U] = tcram1REG->RAMTHRESHOLD;
        config_reg->CONFIG_RAMINTCTRL[0U] = tcram1REG->RAMINTCTRL;
        config_reg->CONFIG_RAMTEST[0U] = tcram1REG->RAMTEST;
        config_reg->CONFIG_RAMADDRDECVECT[0U] = tcram1REG->RAMADDRDECVECT;
        /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "LDRA Tool issue" */
        config_reg->CONFIG_RAMCTRL[1U] = tcram2REG->RAMCTRL;
        config_reg->CONFIG_RAMTHRESHOLD[1U] = tcram2REG->RAMTHRESHOLD;
        config_reg->CONFIG_RAMINTCTRL[1U] = tcram2REG->RAMINTCTRL;
        config_reg->CONFIG_RAMTEST[1U] = tcram2REG->RAMTEST;
        config_reg->CONFIG_RAMADDRDECVECT[1U] = tcram2REG->RAMADDRDECVECT;
    }
}
systemGetConfigValue()
void systemGetConfigValue (system_config_reg_t * config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
Parameters
in *config_reg pointer to the struct to which the initial or current value of the configuration registers need to be stored
in type whether initial or current value of the configuration registers need to be stored
InitialValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
CurrentValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
This function will copy the initial or current value (depending on the parameter 'type') of the configuration registers to the struct pointed by config_reg
Definition at line 488 of file system.c.
{
    if (type == InitialValue)
    {
        config_reg->CONFIG_SYSPC1 = SYS_SYSPC1_CONFIGVALUE;
        config_reg->CONFIG_SYSPC2 = SYS_SYSPC2_CONFIGVALUE;
        config_reg->CONFIG_SYSPC7 = SYS_SYSPC7_CONFIGVALUE;
        config_reg->CONFIG_SYSPC8 = SYS_SYSPC8_CONFIGVALUE;
        config_reg->CONFIG_SYSPC9 = SYS_SYSPC9_CONFIGVALUE;
        config_reg->CONFIG_CSDIS = SYS_CSDIS_CONFIGVALUE;
        config_reg->CONFIG_CDDIS = SYS_CDDIS_CONFIGVALUE;
        config_reg->CONFIG_GHVSRC = SYS_GHVSRC_CONFIGVALUE;
        config_reg->CONFIG_VCLKASRC = SYS_VCLKASRC_CONFIGVALUE;
        config_reg->CONFIG_RCLKSRC = SYS_RCLKSRC_CONFIGVALUE;
        config_reg->CONFIG_MSTGCR = SYS_MSTGCR_CONFIGVALUE;
        config_reg->CONFIG_MINITGCR = SYS_MINITGCR_CONFIGVALUE;
        config_reg->CONFIG_MSINENA = SYS_MSINENA_CONFIGVALUE;
        config_reg->CONFIG_PLLCTL1 = SYS_PLLCTL1_CONFIGVALUE_2;
        config_reg->CONFIG_PLLCTL2 = SYS_PLLCTL2_CONFIGVALUE;
        config_reg->CONFIG_UERFLAG = SYS_UERFLAG_CONFIGVALUE;
        /*SAFETYMCUSW 139 S MR:13.7 <APPROVED> "Hardware status bit read check" */
        if(LPO_TRIM_VALUE != 0xFFFFU)
        {
            config_reg->CONFIG_LPOMONCTL = SYS_LPOMONCTL_CONFIGVALUE_1;
        }
        else
        {
            config_reg->CONFIG_LPOMONCTL = SYS_LPOMONCTL_CONFIGVALUE_2;
        }
        config_reg->CONFIG_CLKTEST = SYS_CLKTEST_CONFIGVALUE;
        config_reg->CONFIG_DFTCTRLREG1 = SYS_DFTCTRLREG1_CONFIGVALUE;
        config_reg->CONFIG_DFTCTRLREG2 = SYS_DFTCTRLREG2_CONFIGVALUE;
        config_reg->CONFIG_GPREG1 = SYS_GPREG1_CONFIGVALUE;
        config_reg->CONFIG_RAMGCR = SYS_RAMGCR_CONFIGVALUE;
        config_reg->CONFIG_BMMCR1 = SYS_BMMCR1_CONFIGVALUE;
        config_reg->CONFIG_MMUGCR = SYS_MMUGCR_CONFIGVALUE;
        config_reg->CONFIG_CLKCNTL = SYS_CLKCNTL_CONFIGVALUE;
        config_reg->CONFIG_ECPCNTL = SYS_ECPCNTL_CONFIGVALUE;
        config_reg->CONFIG_DEVCR1 = SYS_DEVCR1_CONFIGVALUE;
        config_reg->CONFIG_SYSECR = SYS_SYSECR_CONFIGVALUE;
        config_reg->CONFIG_PLLCTL3 = SYS2_PLLCTL3_CONFIGVALUE_2;
        config_reg->CONFIG_STCCLKDIV = SYS2_STCCLKDIV_CONFIGVALUE;
        config_reg->CONFIG_CLK2CNTL = SYS2_CLK2CNTL_CONFIGVALUE;
        config_reg->CONFIG_VCLKACON1 = SYS2_VCLKACON1_CONFIGVALUE;
        config_reg->CONFIG_CLKSLIP = SYS2_CLKSLIP_CONFIGVALUE;
        config_reg->CONFIG_EFC_CTLEN = SYS2_EFC_CTLEN_CONFIGVALUE;
    }
    else
    {
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "LDRA Tool issue" */
        config_reg->CONFIG_SYSPC1 = systemREG1->SYSPC1;
        config_reg->CONFIG_SYSPC2 = systemREG1->SYSPC2;
        config_reg->CONFIG_SYSPC7 = systemREG1->SYSPC7;
        config_reg->CONFIG_SYSPC8 = systemREG1->SYSPC8;
        config_reg->CONFIG_SYSPC9 = systemREG1->SYSPC9;
        config_reg->CONFIG_CSDIS = systemREG1->CSDIS;
        config_reg->CONFIG_CDDIS = systemREG1->CDDIS;
        config_reg->CONFIG_GHVSRC = systemREG1->GHVSRC;
        config_reg->CONFIG_VCLKASRC = systemREG1->VCLKASRC;
        config_reg->CONFIG_RCLKSRC = systemREG1->RCLKSRC;
        config_reg->CONFIG_MSTGCR = systemREG1->MSTGCR;
        config_reg->CONFIG_MINITGCR = systemREG1->MINITGCR;
        config_reg->CONFIG_MSINENA = systemREG1->MSINENA;
        config_reg->CONFIG_PLLCTL1 = systemREG1->PLLCTL1;
        config_reg->CONFIG_PLLCTL2 = systemREG1->PLLCTL2;
        config_reg->CONFIG_UERFLAG = systemREG1->SYSPC10;
        config_reg->CONFIG_LPOMONCTL = systemREG1->LPOMONCTL;
        config_reg->CONFIG_CLKTEST = systemREG1->CLKTEST;
        config_reg->CONFIG_DFTCTRLREG1 = systemREG1->DFTCTRLREG1;
        config_reg->CONFIG_DFTCTRLREG2 = systemREG1->DFTCTRLREG2;
        config_reg->CONFIG_GPREG1 = systemREG1->GPREG1;
        config_reg->CONFIG_RAMGCR = systemREG1->RAMGCR;
        config_reg->CONFIG_BMMCR1 = systemREG1->BMMCR1;
        config_reg->CONFIG_MMUGCR = systemREG1->CPURSTCR;
        config_reg->CONFIG_CLKCNTL = systemREG1->CLKCNTL;
        config_reg->CONFIG_ECPCNTL = systemREG1->ECPCNTL;
        config_reg->CONFIG_DEVCR1 = systemREG1->DEVCR1;
        config_reg->CONFIG_SYSECR = systemREG1->SYSECR;
        /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "LDRA Tool issue" */
        config_reg->CONFIG_PLLCTL3 = systemREG2->PLLCTL3;
        config_reg->CONFIG_STCCLKDIV = systemREG2->STCCLKDIV;
        config_reg->CONFIG_CLK2CNTL = systemREG2->CLK2CNTL;
        config_reg->CONFIG_VCLKACON1 = systemREG2->VCLKACON1;
        config_reg->CONFIG_CLKSLIP = systemREG2->CLKSLIP;
        config_reg->CONFIG_EFC_CTLEN = systemREG2->EFC_CTLEN;
    }
}
systemInit()
void systemInit (void)
Initializes System Driver.
This function initializes the System driver.
Set up flash address and data wait states based on the target CPU clock frequency The number of address and data wait states for the target CPU clock frequency are specified in the specific part's datasheet.
Configure the LPO such that HF LPO is as close to 10MHz as possible
Wait for PLLs to start up and map clock domains to desired clock sources
set ECLK pins functional mode
set ECLK pins default output value
set ECLK pins output direction
set ECLK pins open drain enable
set ECLK pins pullup/pulldown enable
set ECLK pins pullup/pulldown select
Setup ECLK
Definition at line 334 of file system.c.
References checkefcSelfTest(), efcCheck(), FALSE, muxInit(), periphInit(), selftestFailNotification(), and setupPLL().
{
    uint32 efcCheckStatus;
/* USER CODE BEGIN (15) */
/* USER CODE END */
    /* Configure PLL control registers and enable PLLs.
     * The PLL takes (127 + 1024 * NR) oscillator cycles to acquire lock.
     * This initialization sequence performs all the tasks that are not
     * required to be done at full application speed while the PLL locks.
     */
    setupPLL();
/* USER CODE BEGIN (16) */
/* USER CODE END */
    /* Run eFuse controller start-up checks and start eFuse controller ECC self-test.
     * This includes a check for the eFuse controller error outputs to be stuck-at-zero.
     */
    efcCheckStatus = efcCheck();
/* USER CODE BEGIN (17) */
/* USER CODE END */
    /* Enable clocks to peripherals and release peripheral reset */
    periphInit();
/* USER CODE BEGIN (18) */
/* USER CODE END */
    /* Configure device-level multiplexing and I/O multiplexing */
    muxInit();
/* USER CODE BEGIN (19) */
/* USER CODE END */
    if(efcCheckStatus == 0U)
    {
        /* Wait for eFuse controller self-test to complete and check results */
        if (checkefcSelfTest() == FALSE) /* eFuse
       controller ECC logic self-test failed */
        {
            selftestFailNotification(EFCCHECK_FAIL1); /* device operation
       is not reliable */
        }
    }
    else if(efcCheckStatus == 2U)
    {
        /* Wait for eFuse controller self-test to complete and check results */
        if (checkefcSelfTest() == FALSE) /* eFuse
       controller ECC logic self-test failed */
        {
            selftestFailNotification(EFCCHECK_FAIL1); /* device operation
       is not reliable */
        }
        else
        {
            selftestFailNotification(EFCCHECK_FAIL2);
        }
    }
    else
    {
    /* Empty */
    }
/* USER CODE BEGIN (20) */
/* USER CODE END */
    setupFlash();
/* USER CODE BEGIN (21) */
/* USER CODE END */
    trimLPO();
/* USER CODE BEGIN (23) */
/* USER CODE END */
    mapClocks();
/* USER CODE BEGIN (24) */
/* USER CODE END */
    systemREG1->SYSPC1 = 0U;
    systemREG1->SYSPC4 = 0U;
    systemREG1->SYSPC2 = 1U;
    systemREG1->SYSPC7 = 0U;
    systemREG1->SYSPC8 = 0U;
    systemREG1->SYSPC9 = 1U;
    systemREG1->ECPCNTL = (uint32)((uint32)0U << 24U)
                        | (uint32)((uint32)0U << 23U)
                        | (uint32)((uint32)(8U - 1U) & 0xFFFFU);
/* USER CODE BEGIN (25) */
/* USER CODE END */
}
tcmflashGetConfigValue()
void tcmflashGetConfigValue (tcmflash_config_reg_t * config_reg, config_value_type_t type)
Get the initial or current values of the configuration registers.
Parameters
in *config_reg pointer to the struct to which the initial or current value of the configuration registers need to be stored
in type whether initial or current value of the configuration registers need to be stored
InitialValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
CurrentValue: initial value of the configuration registers will be stored in the struct pointed by config_reg
This function will copy the initial or current value (depending on the parameter 'type') of the configuration registers to the struct pointed by config_reg
Definition at line 592 of file system.c.
{
    if (type == InitialValue)
    {
        config_reg->CONFIG_FRDCNTL = TCMFLASH_FRDCNTL_CONFIGVALUE;
        config_reg->CONFIG_FEDACCTRL1 = TCMFLASH_FEDACCTRL1_CONFIGVALUE;
        config_reg->CONFIG_FEDACCTRL2 = TCMFLASH_FEDACCTRL2_CONFIGVALUE;
        config_reg->CONFIG_FEDACSDIS = TCMFLASH_FEDACSDIS_CONFIGVALUE;
        config_reg->CONFIG_FBPROT = TCMFLASH_FBPROT_CONFIGVALUE;
        config_reg->CONFIG_FBSE = TCMFLASH_FBSE_CONFIGVALUE;
        config_reg->CONFIG_FBAC = TCMFLASH_FBAC_CONFIGVALUE;
        config_reg->CONFIG_FBFALLBACK = TCMFLASH_FBFALLBACK_CONFIGVALUE;
        config_reg->CONFIG_FPAC1 = TCMFLASH_FPAC1_CONFIGVALUE;
        config_reg->CONFIG_FPAC2 = TCMFLASH_FPAC2_CONFIGVALUE;
        config_reg->CONFIG_FMAC = TCMFLASH_FMAC_CONFIGVALUE;
        config_reg->CONFIG_FLOCK = TCMFLASH_FLOCK_CONFIGVALUE;
        config_reg->CONFIG_FDIAGCTRL = TCMFLASH_FDIAGCTRL_CONFIGVALUE;
        config_reg->CONFIG_FEDACSDIS2 = TCMFLASH_FEDACSDIS2_CONFIGVALUE;
    }
    else
    {
    /*SAFETYMCUSW 134 S MR:12.2 <APPROVED> "LDRA Tool issue" */
        config_reg->CONFIG_FRDCNTL = flashWREG->FRDCNTL;
        config_reg->CONFIG_FEDACCTRL1 = flashWREG->FEDACCTRL1;
        config_reg->CONFIG_FEDACCTRL2 = flashWREG->FEDACCTRL2;
        config_reg->CONFIG_FEDACSDIS = flashWREG->FEDACSDIS;
        config_reg->CONFIG_FBPROT = flashWREG->FBPROT;
        config_reg->CONFIG_FBSE = flashWREG->FBSE;
        config_reg->CONFIG_FBAC = flashWREG->FBAC;
        config_reg->CONFIG_FBFALLBACK = flashWREG->FBFALLBACK;
        config_reg->CONFIG_FPAC1 = flashWREG->FPAC1;
        config_reg->CONFIG_FPAC2 = flashWREG->FPAC2;
        config_reg->CONFIG_FMAC = flashWREG->FMAC;
        config_reg->CONFIG_FLOCK = flashWREG->FLOCK;
        config_reg->CONFIG_FDIAGCTRL = flashWREG->FDIAGCTRL;
        config_reg->CONFIG_FEDACSDIS2 = flashWREG->FEDACSDIS2;
    }
}
trimLPO()
void trimLPO (void)
Initialize Lpo:
 Load TRIM values from OTP if present else load user defined values
Definition at line 146 of file system.c.
{
/* USER CODE BEGIN (4) */
/* USER CODE END */
    /*SAFETYMCUSW 139 S MR:13.7 <APPROVED> "Hardware status bit read check" */
    if(LPO_TRIM_VALUE != 0xFFFFU)
    {
        systemREG1->LPOMONCTL = (uint32)((uint32)1U << 24U)
                                | LPO_TRIM_VALUE;
    }
    else
    {
        systemREG1->LPOMONCTL = (uint32)((uint32)1U << 24U)
                                 | (uint32)((uint32)16U << 8U)
                                 | 16U;
    }
/* USER CODE BEGIN (5) */
/* USER CODE END */
}